### ISSUE TITLE
Groep: Goed kijken naar flow van nieuwe / niet ingelogde gebruikers (juiste momenten vragen om login, bijv bij besloten groep) [2]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#1]

**Comment by violetmeerdink** [comment]
voorbeeld: in gesloten test groep voor aanjagers een doc gecreeerd (test doc samenwerking) en permissieniveau op 'iedereen, publiek zichtbaar' gezet. Uitgelogd in andere brower en gezocht via zoekfunctie naar dit doc, kom in zoekresultaten, als je er op klikt dan foutmelding 'helaas....' 
optie om in een besloten groep geen permissieniveau publiek op te nemen.

**Comment by bartjkdp** [comment]
Dit is inmiddels opgelost.
