### ISSUE TITLE
Beheerpaneel: menu-items versleepbaar maken

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#100]
Nu kun je de menu-items nog niet verplaatsen.

**Comment by bartjkdp** [comment]
Je kunt menu-items verslepen vanaf commit 02ba9f5

![image](https://user-images.githubusercontent.com/5213690/35198409-c5196e72-feee-11e7-98a1-a8b500bd7a97.png)

**Comment by jfaasen** [comment]
@bartjkdp In firefox werkt het in IE werkt slepen niet.

**Comment by bartjkdp** [comment]
Er miste een Polyfill voor IE (pff IE ook). Ik heb 'm toegevoegd, als het goed is werkt het strak wel (eind van de avond) wel.

**Comment by jfaasen** [comment]
Je kunt ze nu wel slepen in IE maar ze blijven niet staan, daar kan ik helaas geen printscreen van maken ;-)

**Comment by bartjkdp** [comment]
Een basis drag-and-drop werkt. Het lijkt door een verwarrende animatie onder IE net alsof het item terugspringt, al is dit niet zo. We hebben hier onder #112 een nieuw ticket voor aangemaakt. De basis werkt, dus dit ticket kan voor nu dicht.
