### ISSUE TITLE
Exports maken voor groepsleden en agenda-items

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#101]
We willen graag een knopje terug laten komen voor beheerders om een export te maken van agenda-items en groepsleden.

**Comment by bartjkdp** [comment]
Voor groepen is het toegevoegd in b01ea90. Voor agenda-items moet het nog gebeuren, maar levert het exporteren van e-mailadressen voor agenda-items geen problemen op @ziemerink?

**Comment by jfaasen** [comment]
@bartjkdp zie knop wel om export te kunnen maken bij groepbewerken maar krijg geen popup oid met export.

**Comment by bartjkdp** [comment]
Bij mij wordt gewoon de download gestart wanneer je op "exporteer" klikt.

**Comment by ziemerink** [comment]
Ook dit moet je wel aanzetten in het template!

**Comment by bartjkdp** [comment]
Oke er zat nog een klein foutje in waardoor de optie niet verborgen werd wanneer de functie uitstaat. De configuratieoptie is nu toegevoegd aan het template. Eerst aanzetten, dan werkt het.  Komt ook vanavond online. cceb62e

**Comment by jfaasen** [comment]
Yes, werkt in IE en in firefox. Indien ook op safari, sluiten!

**Comment by jfaasen** [comment]
@bartjkdp nog kleine toevoeging. Export agenda items zie ik nog niet maar daar is nu ander ticket voor toch?

**Comment by bartjkdp** [comment]
Ik heb exporteren van agenda-items toegevoegd in 9fea4b9

**Comment by jfaasen** [comment]
@bartjkdp ik kan deze optie nog niet vinden.

**Comment by jfaasen** [comment]
Inmiddels wel kunnen vinden. Werkt alleen voor beheerder, graag ook voor deelsitebeheerders. En export zie je geen e-mail adressen.

**Comment by bartjkdp** [comment]
Deze functie werkt voor iedereen die het evenement kan wijzigen, dus ook de deelsitebeheerder. In de export zie je wel e-mailadressen op het moment dat je deelsitebeheerder bent. Vanwege privacy-redenen kunnen groepsbeheerders de e-mailadressen niet zien.

**Comment by bartjkdp** [comment]
In de commit 3908f56 heb ik de delimiter van ```,``` naar ```;``` veranderd. Nu worden de kolommen standaard goed gedetecteerd in Excel.

**Comment by jfaasen** [comment]
Werkt!
