### ISSUE TITLE
Notificaties: voor groepen beter uitwerken

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#104]
Het is nog lastig om als lid op de hoogte te blijven van activiteiten binnen de groep. Daarom willen we het mogelijk maken om je als lid te abonneren op activiteiten van de groep via het notificatie-systeem.

- [x] Voor leden komt bij de notificaties een overzicht van alle groepen die ze volgen. Standaard staat dit aan.
- [x] Er wordt iedere dag een mailtje gestuurd naar leden voor ongelezen notificaties.

Verder wordt ook het periodiek overzicht van de site (het mailtje met een overzicht van ongelezen content) beter configureerbaar:

- [x] Standaard optie voor "updates ontvangen" configureerbaar maken voor deelsite beheerder. Standaard is dit wekelijks.

**Comment by bartjkdp** [comment]
Het laatste punt noteer ik als prio 2

**Comment by bartjkdp** [comment]
Vanaf d6f053c kan de deelsite-beheerder ook de standaard update instellen.

**Comment by bartjkdp** [comment]
Je kunt nu onder acties instellen of je notificaties voor een groep wil ontvangen

![image](https://user-images.githubusercontent.com/5213690/35437803-4a61b8e8-0294-11e8-9252-9ec57eae6253.png)

![image](https://user-images.githubusercontent.com/5213690/35437805-4ec601c8-0294-11e8-8d0a-eaafd01b1049.png)

**Comment by bartjkdp** [comment]
De gebruiker ontvangt na 2 uur een mail wanneer hij niet op de site is geweest met een melding dat er nieuwe notificaties klaar staan. De gebruiker ontvangt deze mail maximaal 1x per 4 uur.

**Comment by jfaasen** [comment]
@bartjkdp 
Ik zie nu dat dit alleen aanstaat op kia
![afbeelding](https://user-images.githubusercontent.com/34096240/35513834-9917f8f4-0504-11e8-9ed0-7e851f59dba9.png)

updates ontvangen staat niets ingesteld (of is dit aan de achterkant al geregeld nu?)

Bij groepen waar ik lid van ben staan notificaties uit.
![afbeelding](https://user-images.githubusercontent.com/34096240/35513907-ce306896-0504-11e8-8c73-cc817948740b.png)

**Comment by bartjkdp** [comment]
We zijn er bijna. Er is zojuist een functie bijgekomen om notificaties als beheerder te beheren. Daarnaast kan de gebruiker óók bij z'n interesses groepsnotificaties instellen, heb je mooi 1 overzicht:

![image](https://user-images.githubusercontent.com/5213690/35566272-0f01196c-05c1-11e8-9ca6-962e02c7a4b6.png)

**Comment by bartjkdp** [comment]
Notificaties zijn voor iedereen ingesteld. Ik krijg in ieder geval allerlei mailtjes nu. Controleren en sluiten?

**Comment by jfaasen** [comment]
Hoi Bart,
Ik voel me even blond maar er is onduidelijkheid. De schuifjes staan wel aan maar er wordt geen mail gestuurd. Maar het vinkje meldingen per e-mail staat uit. Maar dit is toch de functie als je van alle post en push mail wil? Of moet deze aanstaan? Bij updates ontvangen staat overigens niets.

![afbeelding](https://user-images.githubusercontent.com/34096240/35624004-e404a59e-068d-11e8-93b0-74734e1ac13f.png)

Horen het graag!

**Comment by bartjkdp** [comment]
Met het vinkje kun je alles aan of alles uitzetten. Dus als je het vinkje uit hebt staan, kun je ook de schuifjes niet instellen. Misschien moet ik er voor zorgen dat alle schuifjes grijs worden als het vinkje uitstaat.

**Comment by bartjkdp** [comment]
In #154 is een actie genoteerd om duidelijker te maken dat "Stuur mij meldingen per e-mail" een master-switch is
