### ISSUE TITLE
Groepen: mogelijkheid om groepen uit te lichten

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#105]
Het zou mooi zijn als je groepen ook kan uitlichten waardoor bepaalde groepen eerder tonen.

**Comment by bartjkdp** [comment]
Toegevoegd aan ea5fd65. Je kunt nu groepen uitlichten, deze komen als eerste.

![image](https://user-images.githubusercontent.com/5213690/35198897-02c9735a-fef6-11e7-9324-c2feeb517aa9.png)

**Comment by jfaasen** [comment]
Werkt netjes! getest in IE en Firefox hoe wordt de kleur alleen bepaald? hierboven lijkt het alsof hij de template kleur pakt maar bij KIA is het rood. Zou mooi zijn als dat dan roze is.

**Comment by bartjkdp** [comment]
Als het goed is komt de kleur overeen met de tertiaire kleur in het beheerpaneel.

**Comment by jfaasen** [comment]
yes klopt, opnemen in plug-in overzicht?! kan daarna afgerond worden

**Comment by bartjkdp** [comment]
Wat moet ik opnemen in het plugin-overzicht?

**Comment by jfaasen** [comment]
Ik heb regel toegevoegd aan: https://help.pleio.nl/index.php?title=Totaaloverzicht
kan gesloten worden.
