### ISSUE TITLE
Ik zou de benaming wijzigen van "verlaat groep". Ik zou er van maken "Uitschrijven groep" 

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#107]
In het begin van Pleio noemde we dit ook verlaat groep, mensen dachten dan dat als ze daarmee voor nu de groep verlaten maar besefte niet dat ze zich uitschreven voor de groep.
Wellicht is opzeggen nog beter!

**Comment by bartjkdp** [comment]
Nou ik heb dit gewoon aangepast, om consistent te zijn met het oude Pleio. Opgelost in ee1402a.

**Comment by jfaasen** [comment]
Dit proces getest op IE en firefox en werkt. ticket sluiten?
