### ISSUE TITLE
Groepen: Toon groepseigenaar in de lijst

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#108]
In de lijst met leden wordt voor ieder lid een actie getoond (maak beheerder, verwijder), maar bij de groepseigenaar staat niets. Dit is verwarrend. Voeg "Groepseigenaar" toe.

**Comment by bartjkdp** [comment]
Opgelost in e559620

**Comment by jfaasen** [comment]
Getest in IE en Firefox. Werkt keurig voor beheerder en eigenaar! Je ontvangt alleen nog geen e-mail als je groepsbeheerder bent gemaakt. Overigens heeft functie nu beheerder. Misschien verwarrend met deelsitebeheerder? groepsbeheerder van maken? 
En misschien is het wel goed om eigenaar en groepsbeheerders ergens nog terug te laten komen zodat mensen snel zien met wie ze contact kunnen opnemen?

**Comment by bartjkdp** [comment]
Ik kan ze wel terug laten komen in de gebruikerslijst op het moment dat de gebruiker de rechten niet  heeft, maar dan alleen als weergave.

**Comment by bartjkdp** [comment]
Gebruikers kunnen nu zien wie de beheerders en eigenaar zijn/is. Vanaf e4a4721

**Comment by jfaasen** [comment]
Sluiten. verbetering van de zichtbaarheid als wens genoteerd in #113
