### ISSUE TITLE
CMS: Permissies van pagina's configureerbaar maken

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#109]
Het is nu nog niet mogelijk om permissies van pagina's in te stellen wanneer geavanceerd permissiebeheer aanstaat. Dit wel mogelijk maken.

**Comment by bartjkdp** [comment]
Opgelost in 88cf843

**Comment by jfaasen** [comment]
getest in IE en Firefox werkt. 
Zou deze melding bij pagina's veranders kunnen worden door 'log-in om de pagina te kunnen bekijken'?
![afbeelding](https://user-images.githubusercontent.com/34096240/35224603-d5083574-ff85-11e7-874f-9dcb84d1638c.png)

**Comment by jfaasen** [comment]
@bartjkdp heb jij safari getest?

**Comment by ziemerink** [comment]
Waar kan ik dat instellen? Zie de optie niet!

**Comment by jfaasen** [comment]
@ziemerink bij pagina bewerken.

**Comment by ziemerink** [comment]
In welke pagina's zit het dan in? Niet in Blog, niet in CMS niet in WIIKI ik kijk op https://demo.odc.pleio.nl/.

**Comment by bartjkdp** [comment]
@ziemerink je moet even "Geavanceerd permissie-beheer" aanzetten in de plugin, standaard staat dit uit.

**Comment by bartjkdp** [comment]
@jfaasen vanaf 56c8b6f wordt de gebruiker gevraagd om in te loggen.

**Comment by jfaasen** [comment]
Hey Bart, het lijkt zo nogsteeds een 404'tje. Even overleg
![afbeelding](https://user-images.githubusercontent.com/34096240/35326919-6b19befc-00f8-11e8-86b5-faf4bf40dfe7.png)

**Comment by bartjkdp** [comment]
Hmm dat is gek, heb je de pagina vernieuwd? Op exact dezelfde URL zie ik dit:

![image](https://user-images.githubusercontent.com/5213690/35327173-3949f33c-00f9-11e8-81f2-17c858776fd2.png)

**Comment by jfaasen** [comment]
ja, ik had hem al weer openbaar gezet.

**Comment by bartjkdp** [comment]
Ahzo wat je verwacht was mij even niet helemaal duidelijk. Volgens mij hebben we het nu over het aanpassen van de tekst wanneer een item niet zichtbaar is.

De tekst is volgens mij wel degelijk aangepast, nu wordt de gebruiker gevraagd om in te loggen.

**Comment by jfaasen** [comment]
@bartjkdp past tekst nog aan. Daarna sluiten

**Comment by bartjkdp** [comment]
Teksten zijn nogmaals aangepast in b749d77. Ticket kan dicht.
