### ISSUE TITLE
Beheer: Mogelijkheid toevoegen om standaardmeldingen in te stellen

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#110]
Het is voor beheerders momenteel niet mogelijk om de standaardmeldingen voor gebruikers in te stellen. Graag zouden we een optie willen toevoegen in het beheerpaneel waarmee de beheerder de mogelijkheid krijgt om de standaardmeldingen in te stellen. Als laatste zouden we ook graag de mogelijkheid willen krijgen om met een klik op de knop meldingen voor alle gebruikers aan te zetten.

**Comment by bartjkdp** [comment]
Inmiddels mogelijk via ```admin/plugin_settings/pleio_template``` en ```admin/administer_utilities/notifications```
