### ISSUE TITLE
Beheer: Bij de afzender van de mailtjes wordt Pleio weergegeven, graag de naam van de deelsite plaatsen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#111]
Nu wordt er als afzender Pleio gebruikt, het zou mooier zijn als hier de naam van de deelsite staat.

**Comment by bartjkdp** [comment]
Opgelost in c010af6. Verzendernaam is nu de naam van de deelsite.

**Comment by jfaasen** [comment]
Werkt! kan gesloten worden
![afbeelding](https://user-images.githubusercontent.com/34096240/35327276-7fe0c172-00f9-11e8-9795-9ac58267d8b7.png)
