### ISSUE TITLE
groep: zichtbaarheid eigenaar en groepsbeheerders prominenter maken [3]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#113]
Nu kun je alleen door de lijst door te scrollen zien wie eigenaar en groepsbeheerders zijn. Wens om (met osage) te kijken hoe je hier een overzicht van kunt maken onder i.  opdrachtgever financier nodig.

**Comment by bartjkdp** [comment]
Voor de duidelijkheid, onder i is dus het informatie-scherm van de groep dat je kunt zien wanneer je op het icoontje "i" drukt.

**Comment by jfaasen** [comment]
extra toevoeging. Namen ook aanklikbaar maken ivm contact opnemen

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#162
