### ISSUE TITLE
Evenementen: Ook externen moeten zich kunnen registreren voor een evenement

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#114]

**Comment by bartjkdp** [comment]
Dit is geen prio 1 en er is bewust voor gekozen om dit niet in te bouwen voor nu.

**Comment by ziemerink** [comment]
De evenementen tool is beperkt, dan kunnen we geen financiering vragen voor functies die wel in de oude zaten maar niet in de nieuwe.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#163
