### ISSUE TITLE
Mobiel groepen: knop lid worden / lidmaatschap aanvragen ontbreekt

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#115]
als je nu op bv een agenda-item klikt op hoofdniveau kom je wel op de groep terecht, direct op de pagina evenementen maar je ziet dan geen knop. Geldt ook voor overige pagina's

**Comment by bartjkdp** [comment]
Opgelost vanaf 1f7a809

**Comment by jfaasen** [comment]
Werkt in IE en Firefox. En op Ipad. Alleen op mobiel nog niet. Daar zie je nergens knopje lid worden/lidmaatschap aanvragen. klopt dat?

**Comment by jfaasen** [comment]
@bartjkdp wat is de status hiervan?

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#164
