### ISSUE TITLE
Wensen van HT gewacht op nieuwe template maar daarin kunnen deze zaken nog niet.

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#116]
Weet jij of het mogelijk is om op het forum HT de nieuwsberichten op een andere plek te krijgen? 

Nu staan de forumdiscussie boven aan. Ik wil liever de nieuwsberichten bovenaan. En de pollvraag staat helemaal verstopt onderaan. Zou die in een (klein) blok ook naar boven kunnen?

Ik verwacht niet dat dit heel veel tijd kost toch?

**Comment by bartjkdp** [comment]
Heeft dit betrekking op het nieuwe template? Ik begrijp niet precies wat hier bedoeld wordt.

**Comment by ziemerink** [comment]
Nee deze wijzigingen in het oude template maar  Toine had haar "beloofd" dat begin januari het nieuwe template er zou zijn en dat dit dan in het nieuwe template mogelijk was.

**Comment by bartjkdp** [comment]
Zou je deze issue dan even kunnen verplaatsen naar Pleio/pleio?
