### ISSUE TITLE
Subgroepen: verbetering van overzicht en toevoegen van leden gewenst [4]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#120]
Zie https://github.com/Pleio/pleio_template/issues/31 voor achtergrond. subgroepen werken functioneel maar het overzicht van subgroepen is nog niet optimaal, zeker voor grote groepen. Ook het aanmaken van grote subgroepen werkt nog niet handig. UI/UX design en verbetering is gewenst.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#165
