### ISSUE TITLE
Afwijkingen Ipad

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#121]
In dit issue punten die op een ipad niet/anders werken dan op de gewone website

- [ ] niet duidelijk dat je je profielfoto kunt aanpassen. Je moet hiervoor de bestaande foto langer aanraken. Dat is anders dan de andere profielitems wijzigen, dan hoef je de ... alleen kort aan te tikken.

**Comment by bartjkdp** [comment]
Ik weet niet of we dit echt moeten oplossen en hoe precies. @jfaasen nog ideeën?

**Comment by SaskiavdM** [comment]
Is ook niet heel essentieel. Voor de nieuwe generatie zal dit toch wel voor zich spreken ;)

**Comment by jfaasen** [comment]
@bartjkdp @SaskiavdM, we maken er op KIA wel een vraag van. En t.z.t. maar even kijken of het op help.pleio terug moet komen. Dit onderwerp nog even open laten staan voor eventuele andere dingen

**Comment by jfaasen** [comment]
Notificaties niet scrolbaar op ipad

![afbeelding](https://user-images.githubusercontent.com/34096240/36154299-442947c0-10d1-11e8-9331-15b267dd3bbb.png)

**Comment by jfaasen** [comment]
werkt inmiddels kan gesloten worden.
