### ISSUE TITLE
Nadenken over mogelijkheden tot beperken aanmaken van content-typen op site en groepsniveau

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#123]
Nu is er alleen schuifje bestanden. Indien die aan gaat zou het mooi zijn als er gelijk een schuifje bestanden en mappen door leden aanmaken volgt (die je aan/uit kan zetten) in Pleio oud is die keuze er ook.

**Comment by bartjkdp** [comment]
Zou je dit ook willen instellen voor andere typen content?

**Comment by jfaasen** [comment]
@bartjkdp iets voor de CAB om verder over na te denken? 
volgensmij kon je nu alleen discussies beperken, dat zit ergens in tabblad twee verstopt... @ziemerink of zijn er meer?

**Comment by jfaasen** [comment]
@bartjkdp , #122 heb je gesloten maar deze is wel iets anders dan hierboven Voor KIA is iig op korte termijn nodig:
- [ ] Functie groepen aanmaken alleen voor beheerders (in adminpannel aan uit kunnen zetten)
- [ ] bestanden/mappen aanmaken in groepen kunnen beperken tot alleen groepsbeheerders

overige functies bespreken in CAB

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#166
