### ISSUE TITLE
Widget: agenda items voor homepagina

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#124]
in CMS blok met agenda items kunnen aanmaken. Net zoals je ze in groep kunt zien.

**Comment by bartjkdp** [comment]
Vanaf b36d085 is er een widget beschikbaar voor evenementen.

**Comment by jfaasen** [comment]
Ziet er mooi uit! Ik mis onderaan alleen nog linkje naar meer agenda items. Kun je dat nog inbouwen?

**Comment by bartjkdp** [comment]
Deze is toegevoegd in 34814e4

**Comment by jfaasen** [comment]
@bartjkdp werkt en mooi icoontje! term 'alles' moest ik even over denken maar is smaak denk ik. Meer zou ook kunnen maar voor nu sluiten!
