### ISSUE TITLE
Nieuwe vraag aanmaken werkt niet

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#125]
Op hoofdniveau werkt het niet om een nieuwe vraag aan te maken. Het knopje ontbreekt.

**Comment by bartjkdp** [comment]
Dit is opgelost in 19e1b86. Vanaf nu is het knopje er weer.

**Comment by jfaasen** [comment]
@bartjkdp Werkt. Ik zie alleen dat forum nu verandert is in discussies? ipv vragen?

**Comment by jfaasen** [comment]
Oke, ik dacht juist dat ze op hoofdniveau een forum (met vragen wilde naast discussies maar dat bespreken we de 8e dan wel. Voor nu sluiten
