### ISSUE TITLE
Functionaliteiten: toevoegknoppen naar beneden

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#126]
De toevoegknoppen van

- [ ] Blog

- [ ] Discussie

- [ ] Vragen

- [ ] Wiki

- [ ] taken

Staan nog in de header van de groep en moeten daaronder worden geplaatst

**Comment by bartjkdp** [comment]
Dit is opgelost in 4b1b2e4. Alle toevoeg-knoppen zijn verplaatst naar de container van de groep.

**Comment by jfaasen** [comment]
Werkt!
