### ISSUE TITLE
Afwijkingen mobiele versie

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#128]
Alleen getest in safari!
![image](https://user-images.githubusercontent.com/34911394/35482058-c3f17486-042f-11e8-9dce-bada783bf9b3.png)
Deelsitebeheerder kan in de mobiele versie wel heel makkelijk van alles verwijderen

![image](https://user-images.githubusercontent.com/34911394/35482063-d1f5f642-042f-11e8-8b5a-309a0ce64e0b.png)
Na gebruik van het menu schuift het niet automatisch terug als je iets gekozen hebt. Als je ernaast tikt schuift het wel terug en kun je verder werken. Maar het is logischer als na het maken van een menukeuze het menu terugschuift

@jfaasen Kun jij de overige beelden van commentaar voorzien?
![image](https://user-images.githubusercontent.com/34911394/35482069-ecda451c-042f-11e8-876a-e5387dec2f40.png)

![image](https://user-images.githubusercontent.com/34911394/35482074-00b4616c-0430-11e8-8bb1-5488d65a709b.png)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#167
