### ISSUE TITLE
Statusupdate: laad niet gelijk bij open groep

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#129]
Hey Bart, Statusupdate scherm laadt niet gelijk als je in je groep komt. Pas na f5. Kun je dit oplossen? 

![afbeelding](https://user-images.githubusercontent.com/34096240/35482780-34f20b0a-043a-11e8-8a16-bcc575709853.png)

**Comment by bartjkdp** [comment]
Dit heb ik opgelost in 916f0ba

**Comment by jfaasen** [comment]
@bartjkdp werkt nu wel maar nu merk ik ingelogd wel dat het klikken op groepen lang duurt met laden en je moe f5 en ook zie je dubbele menuitems geselecteerd. Getest in meerdere browsers met meerdere log-ins op twee PC's enig idee wat er aan de hand is?

![afbeelding](https://user-images.githubusercontent.com/34096240/35487793-d0ac0736-047f-11e8-9719-4b1b00786f72.png)

**Comment by bartjkdp** [comment]
De andere problemen zijn inmiddels ook opgelost. Ticket kan dicht.
