### ISSUE TITLE
Rich-text editor toevoegen bij Tweio / statusupdate [1]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#13]

**Comment by bartjkdp** [comment]
Opgelost in 23feb2f

**Comment by jfaasen** [comment]
Werkt, wel een uitgeklede variant. (nog) geen filmpjes of social post. Dit om tijdlijn schoon te houden. Kan wel linken. Voor nu laten we het zo als test. In een later fase met andere deelsitebeheerders nog eens overleg.
