### ISSUE TITLE
Contactgegevens: niet alles is zichtbaar voor andere gebruikers

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#130]
Voor de KIA beheerder heb ik alle gegevens ingevuld, behalve telefoonnummers. Wanneer ik nu met een ander account naar de contactgegevens van de KIA beheerder kijk. Zie ik niet alle ingevulde gegevens.
![image](https://user-images.githubusercontent.com/34911394/35483833-f5fe14d6-0446-11e8-920f-ea660c93cc70.png)
Hoe kan dat?

**Comment by bartjkdp** [comment]
Voor mij (beheerder) is niet alles ingevuld?
![image](https://user-images.githubusercontent.com/5213690/35485203-674f8ea2-045c-11e8-9e6a-667c37085732.png)

**Comment by bartjkdp** [comment]
Die moet je zichtbaar maken, standaard staat ie op privé (grijs)

**Comment by SaskiavdM** [comment]
Die moet in de handleiding ;)
Duidelijk! Ik sluit het issue
