### ISSUE TITLE
Bestandenfunctionaliteit: lees- en schrijfrechten

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#131]
Met het doornemen van de bestandenfunctionaliteit kwam ik het volgende tegen:
als beheerder (van groep en deelsite) heb ik in de testgroep KIA een document geplaatst. Leesrechten voor de groep en schrijfrechten alleen voor mij. 
Met mijn andere account als groepslid (geen deelsitebeheerdersaccount) kan ik het document downloaden, naam wijzigen, lees/schrijfrechten aanpassen, bestand verwijderen, etc
Lijkt mij toch niet de bedoeling?
![image](https://user-images.githubusercontent.com/34911394/35485269-5459d928-045d-11e8-9235-5f1b4e3ae78b.png)

**Comment by bartjkdp** [comment]
Dit kan ik niet reproduceren. Ben je misschien vergeten de pagina te vernieuwen (F5) nadat je de permissies hebt aangepast?

**Comment by SaskiavdM** [comment]
Ik had idd niet refresht. Maar ik was uitgelogd met het beheerdersaccount, waarmee het bestand was geupload, en ingelogd met mijn gewone account. Net gerefresht, en toen kon ik het idd niet meer aanvinken.
Wel vreemd dat ik ondanks uitloggen en inloggen met ander account eerst moet refreshen
Of is dit nerdlogica?

**Comment by bartjkdp** [comment]
Als je uitlogt en inlogt met een ander account hoef je niet te refreshen hoor. Misschien dat je perongeluk toch met het beheer-account was ingelogd?

**Comment by SaskiavdM** [comment]
Hmm, ik weet zeker dat het was zoals ik mailde, maar kan het ook niet meer reproduceren. 
Sluit het issue dus!
