### ISSUE TITLE
Editor: toevoegen aan informatie over de groep en reactie onderdelen

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#132]
editor mist nu bij introductieveld voor groep (links in introteksten e.d. werken ook niet meer daardoor) en ook bij het plaatsen van een reactie bij bv vragen, blogs, discussies mist deze

**Comment by bartjkdp** [comment]
Dit is opgelost in 84eb416

**Comment by jfaasen** [comment]
Werkt!
