### ISSUE TITLE
admin: ledenoverzicht in statistiek klopt niet 

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#133]
ODC of template issue? 
Voor migratie: 
![afbeelding](https://user-images.githubusercontent.com/34096240/35488119-c68a3684-0483-11e8-8bdb-718117ef566b.png)

Na migratie:

![afbeelding](https://user-images.githubusercontent.com/34096240/35488121-dfbe5900-0483-11e8-8775-05e743f12bee.png)

Export aantallen kloppen (juiste) kloppen niet meer met overzicht.

**Comment by bartjkdp** [comment]
Dit heeft niets met het nieuwe template te maken maar is wel verklaarbaar. Wanneer een site een eigen database krijgt migreert het systeem alle gebruikers die ooit content hebben gehad op de site. De gebruikers die geen lid meer zijn worden vervolgens geblokkeerd.

**Comment by jfaasen** [comment]
@bartjkdp uit technisch oogpunt verklaarbaar maar voor deelsitebeheerders levert dit wel verwarring op als statistieken niet kloppen met export. Daarbij ga je er vanuit dat verwijderd ook echt verwijderd is.  Graag even overleg hoe hier mee om te gaan zodat ik het ook binnen RVO en NA kan communiceren.

**Comment by bartjkdp** [comment]
Helaas is er niet echt een andere manier om mee om te gaan. Gebruikers moeten gewoon bestaan in de database om te zorgen dat er content aan kan hangen. In het geval van alles op één database verwijderde je vroeger de gebruiker van de deelsite, maar niet van het hoofdniveau.

**Comment by jfaasen** [comment]
Oke, maar is er dan iets te verzinnen dat je in statistieken een overzicht ziet van actieve leden en inactieve leden ofzo? Dan kunnen eigenaren iig gebruikersaantallen meten. En eventueel ook in een losse export kan terugzien wie er inactief zijn? Bij kennisdelen speelt dit namelijk ook volgensmij.

**Comment by bartjkdp** [comment]
Dat kan natuurlijk wel. Deze issue blijft in ieder geval gesloten omdat het niets met het nieuwe template te maken heeft. Er komt een nieuwe op Pleio/pleio.
