### ISSUE TITLE
Discussies: oude links naar /discussions werken niet meer

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#135]
Om een of andere reden hebben we nu /discussion in de URL, waardoor links naar /discussions niet meer werken. We moeten even nadenken of we alsnog naar /discussions willen gaan, of dat we een rewrite maken om te zorgen dat zowel /discussion als /discussions werkt.

**Comment by bartjkdp** [comment]
Vanaf c18060a heb ik overal ```/discussions``` hernoemd naar ```/discussion```, zodat we weer aansluiten bij de URL structuur van het oude Pleio. We moeten alleen even goed het menu van de groepen en het hoofdmenu nakijken zodra we live gaan om te controleren of alles goed gaat.

**Comment by jfaasen** [comment]
Voor zover ik steekproefgewijs heb kunnen beoordelen is alle oude content zichtbaar.
