### ISSUE TITLE
Groepen: bij het uitnodigen van gebruikers mist visuele feedback na uitnodigen

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#137]
Bij het uitnodigen van lede in de groep vesrchijnt er geen zandlopertje of iets dergelijks zodat je weet dat het prces gestart is. Gebruikers gaan nu meerdere keren klikken!

**Comment by bartjkdp** [comment]
Dit is een bekend probleem en zou eigenlijk generiek opgelost moeten worden. Op meer plekken missen gebruikers visuele feedback wanneer een proces "loopt". Het zou mooi zijn als het knopje verandert in een draaiend cirkeltje of iets dergelijks. We kunnen dit wellicht bij Osage neerleggen om  1 generieke oplossing te maken, dan rollen we hem op verschillende plekken uit.

**Comment by MeneerFab** [comment]
![screen shot 2018-03-13 at 12 32 29](https://user-images.githubusercontent.com/5603405/37339334-a49112d8-26ba-11e8-8e8d-015a3212243b.png)

@bartjkdp Loader toegevoegd, nu nog verder implementeren met formulier.

**Comment by bartjkdp** [comment]
Geimplementeerd met het formulier (op die pagina)

**Comment by jfaasen** [comment]
@bartjkdp @MeneerFab getest in firefox en IE bij uitnodigen leden, ziet er goed uit! Hadden jullie het ook al op andere plekken doorgevoerd die nog getest moesten worden? Anders sluiten!
