### ISSUE TITLE
Agenda: de aangemelde gebruikers worden niet meer getoond

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#138]
Na een migratie wordt voor alle agenda-items de optie "Aanwezigheid registeren" uitgezet. Hierdoor tonen de aangemelde gebruikers niet meer. We willen graag standaard deze optie aanzetten zodat dit probleem zich niet meer voordoet.

**Comment by bartjkdp** [comment]
Dit is opgelost in e390f32. Standaard staat "Aanwezigheid registeren" voor agenda-items nu aan.

**Comment by jfaasen** [comment]
@bartjkdp  Zie deze twee

https://kia.pleio.nl/groups/view/51730042/informatie-voor-aanjagers-kennisplatforms/events/view/54436972/training-werken-met-pleio-nieuwe-template

https://kia.pleio.nl/groups/view/48594512/kennisplatform-juridische-vraagstukken/events/view/54821502/belangstellingsregistratie-leergang-privacy-algemene-verordening-gegevensbescherming-een-goede-voorbereiding-is-het-halve-werk

**Comment by bartjkdp** [comment]
Bedankt voor de melding. Een hele subtiel foutje gemaakt waardoor dit mis is gegaan. Ik heb het opgelost vanaf d188cb2. Heb een migratiescript geschreven om aanmeldingen die in de tussentijd zijn gekomen goed te verwerken, dit moeten we even voor de zekerheid controleren of het goed gaat.

**Comment by bartjkdp** [comment]
Het werkt allemaal nu wel, maar nu gaat het niet goed als er heel veel aanmeldingen zijn, de oneindige scroll doet het nog niet goed. Zie #149

**Comment by jfaasen** [comment]
Deze kan gesloten. Oude aanmeldingen zijn terug. Meer in #149
