### ISSUE TITLE
Groepen: Als deelsitebeheerder gebruikers direct toe kunnen voegen aan een groep (zonder accepteren van uitnodiging)

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#139]
We willen graag een functie toevoegen aan het beheerpaneel waarmee gebruikers die al lid zijn van de site door de beheerder lid gemaakt kunnen worden van een groep, zonder dat er eerst een uitnodigings-traject nodig is.

**Comment by bartjkdp** [comment]
Is het zo dat de management assistentes zelf het wachtwoord hebben van de manager?

**Comment by ziemerink** [comment]
Vaak beschikken management assistentes inderdaad over de account gegevens van hun manager!

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#168
