### ISSUE TITLE
Bestanden: toevoegen aan notificatie-systeem en activiteitenstroom [6]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#140]
Nu wordt er nog geen activiteit gegenereerd bij het uploaden van bestanden en wordt dit ook niet getoond in het notificatiesysteem. We zouden hier graag een functie voor willen toevoegen.

**Comment by jfaasen** [comment]
Als het gemaakt wordt graag ook activiteit bij overschrijven van bestand. Overigens hebben we het eerder over gehad dat het ook een vinkje zou kunnen zijn. Dat je kunt kiezen om statusupdate wel of niet te delen. Meningen zijn er over verdeeld of het wel of niet nodig is. Voor nu kun je iig bij statusupdate de aandacht vestigen op een nieuw bestand. Eventueel afstemming CAB?

**Comment by ziemerink** [comment]
In het kader van de transparantie zou ik zeggen dat er altijd een statusupdate volgt!

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#169
