### ISSUE TITLE
Zoeken: klikken op vergrootglas werkt niet []

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#141]
Zoekterm invullen op enter drukken werkt wel maar op vergrootglas klikken werkt niet. Zwel op hoofd- als op groepsniveau.

**Comment by bartjkdp** [comment]
Dat hoort zo hoor, het zoekglas is geen knopje.

**Comment by jfaasen** [comment]
@bartjkdp ik dacht van wel maar maakt opzich niet uit. Kun je er een knopje van maken of is daar meer voor nodig?

**Comment by MeneerFab** [comment]
@bartjkdp Krijg het in groepsniveau niet aan de praat, het zoekformulier werkt daar weer net anders lijkt het..

**Comment by bartjkdp** [comment]
Vanaf Pleio/pleio_template@7cf5f69 is ook het icoontje in de groep klikbaar.

**Comment by ziemerink** [comment]
Werkt!
