### ISSUE TITLE
Migratie oud/nieuw: wikipagina's tweio's

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#142]
Wikipagina's (en subpagina's) en tweio berichten zijn niet opgenomen: voorbeeld KP innovatie:

![afbeelding](https://user-images.githubusercontent.com/34096240/35638316-13cb3800-06b7-11e8-86e0-0d67c221be05.png)

**Comment by jfaasen** [comment]
@bartjkdp Wat is de status hiervan? Moet wel zsm opgelost worden!

**Comment by bartjkdp** [comment]
Er is een migratiescriptje bijgekomen om wikipagina's te tonen in het nieuwe template met b71e3f4f44eb511a322d2ff09ea1e52c83825ba3, Wireberichten werden al goed getoond.

**Comment by jfaasen** [comment]
Hoi Bart, ze zijn helaas nog niet zichtbaar. Zie groep Innovatie

**Comment by violetmeerdink** [comment]
Hoi Bart, fijn dat je al aan het testen bent. Hoop dat het vandaag gaat lukken. Succes!

**Comment by jfaasen** [comment]
Hoi Bart,

Een deel is wel meegenomen maar niet alle subpagina's. Check bovenstaand voorbeeld naast groep op kia.

ook werken afbeeldingen nog niet lekker, ook niet als ik ze er handmatig opnieuw inzet. Zie het oude voorbeeld:

https://kia-oud.pleio.nl/pages/view/55730422/werkvormen-innovatief-onderzoek

**Comment by bartjkdp** [comment]
Het probleem van de sub-sub pagina's is te vinden in #164 . Verder is alles afgerond, dus we sluiten deze.
