### ISSUE TITLE
Bestanden:  toevoegen van word, excel, powerpoint e.d. incoontjes, net als PDF [4]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#143]
- Word
- Excel
- Powerpoint

**Comment by bartjkdp** [comment]
Hiervoor is ontwerpwerk nodig, wellicht Osage of Fabian?

**Comment by jfaasen** [comment]
geldt ook voor Pleiofile. Wens bij RVO en NA. Ook bij Pleio algemeen als wens noteren?

**Comment by bartjkdp** [comment]
De iconen-set waar pleiofile gebruik van maakt is een andere. De hele stijl daarvan is gebaseerd op [Bootstrap 3](https://glyphicons.bootstrapcheatsheets.com/), maar die heeft ook geen applicatie-specifieke iconen.

We zouden wellicht iconen van [Font Awesome](https://fontawesome.com/icons) als basis kunnen gebruiken?

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#170
