### ISSUE TITLE
Nieuws: Reacties onder nieuwsberichten plaatsen

### ISSUE THREAD

**Issue by LisaGaster** [Pleio/pleio_template#144]
In het beheerpaneel graag mogelijkheid om reacties op nieuwsberichten te kunnen plaatsen op siteniveau

**Comment by jfaasen** [comment]
@bartjkdp a.s. woensdag samen even doorlopen met scope reacties van andere onderdelen. Misschien kunnen we er een gecombineerd ticket van maken.

**Comment by bartjkdp** [comment]
In ab6f30c is dit opgelost.
