### ISSUE TITLE
Activiteiten: video's spelen niet direct af wanneer ze als omslagfoto zijn geplaatst

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#145]
We moeten dit even snel oplossen zodat het wel kan.

**Comment by bartjkdp** [comment]
@ziemerink kun jij even kijken wat dit precies is en of dit echt een probleem is?

**Comment by ziemerink** [comment]
Kan het niet reproduceren, zowel in Google Crome als in Safari en IE11 speelt de video naar aanklikken direct af!

**Comment by bartjkdp** [comment]
@jfaasen weet jij dit nog hoe dit zit?

**Comment by jfaasen** [comment]
Ik kan het niet achterhalen. Voor nu sluiten?
