### ISSUE TITLE
Periodiek overzicht: Opmaak aanpassen naar deelsite

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#147]
Qua inhoud goed. Vind het kleurgebruik alleen niet mooi en niet passen bij het kleurenpallet van KIA. Kan dat niet in kia-groen, kia-roze en zwart oid?

**Comment by bartjkdp** [comment]
@violetmeerdink niet geheel duidelijk wat je bedoelt. Hoe bedoel je dat precies? Kun je een screenshot toevoegen?

**Comment by violetmeerdink** [comment]
![image](https://user-images.githubusercontent.com/34913358/35681070-92236a4c-075c-11e8-8e3c-db5218152c18.png)

**Comment by bartjkdp** [comment]
Helemaal mee eens, mag zeker mooier. We moeten even nadenken over de juiste kleuren...

**Comment by violetmeerdink** [comment]
rijkshuisstijl willen we heel ver van blijven, want het dat is KIA niet. iets met de ia-roze kleur vind ik wel gaaf

**Comment by bartjkdp** [comment]
@jfaasen kun jij, eventueel met Dennis, een voorstel doen?

**Comment by jfaasen** [comment]
@bartjkdp Dennis mag je vragen om ondersteuning

**Comment by bartjkdp** [comment]
@MeneerFab zou jij hier even naar kunnen kijken?

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#171
