### ISSUE TITLE
Online documenten: mogelijkheden onderzoeken voor betere samenwerkingseditor

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#148]
We hebben natuurlijk WebODF waar we nu mee integreren en Etherpad waarmee we zouden kunnen integreren. We kunnen ook onderzoeken of we met andere plugins eenvoudig samenwerkfunctionaliteit kunnen realiseren. Kandidaten zijn:

- [Substance](http://substance.io/)
- [Together.js](https://togetherjs.com/) (bouwblok)
- [Ace editor](https://ace.c9.io/) (alleen als bouwblok, Dropbox paper is hier op gebaseerd)

**Comment by ziemerink** [comment]
Wat mij betreft fase 2

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#172
