### ISSUE TITLE
Agenda: wanneer er veel aanmeldingen zijn wordt dit nog niet optimaal getoond

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#149]
Er zijn te veel profielfoto's op de overzichtspagina en te weinig profielfoto's in het detailoverzicht. Dit moet even gefixt worden!

**Comment by bartjkdp** [comment]
Opgelost in e900b83

**Comment by jfaasen** [comment]
@bartjkdp, Zou wel fijn zijn als je in het overzicht net als bij leden je eerst wat foto's ziet en dan grijze profielen.

![afbeelding](https://user-images.githubusercontent.com/34096240/35917751-896dfb4e-0c0f-11e8-9c1f-13bbc842a808.png)

**Comment by jfaasen** [comment]
@bartjkdp zou je bovenstaande ook nog willen controleren voor groepsleden algemeen? Bij sommige groepen gebeurt het wel andere nog niet.

**Comment by bartjkdp** [comment]
Helaas is het in de oude backend niet eenvoudig om eerst foto's en dan pas grijze poppetjes te tonen :( dan moeten we echt naar de nieuwe backend.
