### ISSUE TITLE
Groepen: links in het oude Pleio hebben een andere URL dan in het nieuwe Pleio

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#151]
Hoi Bart, we merken dat links naar de KP's het niet meer doen. zie verschillen (profile versus view)
Kun je hier wat aan doen of ze laten redirecten? 

https://kia.pleio.nl/groups/view/41371832/kennisplatform-preservation (nieuw)
https://kia.pleio.nl/groups/profile/41371832/kennisplatform-preservation (oud)

**Comment by bartjkdp** [comment]
Dit is opgelost in d55695c

**Comment by jfaasen** [comment]
@violetmeerdink wil jij even laten weten of dit opgelost is dan kunnen we het ticket sluiten.

**Comment by violetmeerdink** [comment]
werkt
