### ISSUE TITLE
Bewaard:  niet alle content kun je nu bewaren [2]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#155]
Er missen onderdelen in de lijst: Keuze? wens om ook bestanden, discussies, statusupdate (en eventueel agenda itemst) te kunnen bewaren. 

![afbeelding](https://user-images.githubusercontent.com/34096240/36102989-4d75bf98-100e-11e8-941d-ac989bba71b4.png)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#175
