### ISSUE TITLE
content bewaren: lijst alle catagorieeen toont leraar.nl?

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#156]
Zie hier: 
![afbeelding](https://user-images.githubusercontent.com/34096240/36103085-a0d7f9b2-100e-11e8-8093-20b36571e5d4.png)

**Comment by bartjkdp** [comment]
Dit is opgelost in 3dad8f8

**Comment by jfaasen** [comment]
Ze zijn idd verdwenen.

**Comment by jfaasen** [comment]
Ze zijn idd verdwenen.
