### ISSUE TITLE
Profiel: website adres blijft niet staan

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#158]
In firefox en chrome kun je wel een webadres invullen maar die blijft niet staan.

**Comment by ziemerink** [comment]
Bij mij werkt het ook zoals verwacht!

**Comment by jfaasen** [comment]
Bij accounts, violet, Christian v.d. Ven en mij werkt het iig niet.

**Comment by bartjkdp** [comment]
Violet heeft er www.nationaalarchief.nl staan,  Christian kan ik niet controleren. Is het misschien een specifieke browser?

**Comment by jfaasen** [comment]
Bij IE en Firefox gebeurt er dit
![afbeelding](https://user-images.githubusercontent.com/34096240/36214831-b7caca62-11aa-11e8-9c48-5e83ac8687ae.png)

na f5:
![afbeelding](https://user-images.githubusercontent.com/34096240/36214846-c268fe58-11aa-11e8-8ce1-fe7d945f2c42.png)

**Comment by bartjkdp** [comment]
Ik heb het geprobeerd in IE11 en Firefox met een testaccount (barttest) maar het lukt mij echt niet om te reproduceren

**Comment by bartjkdp** [comment]
Bij cultureelerfgoed werkt het nog niet goed. Bv in mijn profiel https://intranet.cultureelerfgoed.nl/profile/dick6 vul ik onder Functie 'webmaster' in, en het lijkt in orde maar na verversen is de data weer weg.

Browser:

Google Chrome / Versie 65.0.3325.181
IE 11.0.9900

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#177
