### ISSUE TITLE
Bookmarks: je kunt wel content bewaren maar wordt niet opgeslagen

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#159]

**Comment by jfaasen** [comment]
Wens ivm concequente doorvoering. bookmark omlijning roze maken ipv grijs:
![afbeelding](https://user-images.githubusercontent.com/34096240/36208246-b73b43d6-1198-11e8-8478-5dcc2e5dcb8c.png)

**Comment by bartjkdp** [comment]
Het ging nog fout bij discussies, is nu opgelost. De stijlingwens: volgens mij is het juist consistent om het grijs te houden, je kunt het eventueel met CSS overschrijven als je het er niet mee eens bent ;)

**Comment by jfaasen** [comment]
wbt: styling dingetje maak ik nog even een ander ticketaan. zitten wat inconcequeties in. Misschien maandag even naar kijken.
