### ISSUE TITLE
Leden: overzichtpagina alle leden [2]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#160]
in oude template was overzichtspagina beschikbaar met alle leden als /members. Graag terugbrengen.

**Comment by bartjkdp** [comment]
Dient deze pagina ook zichtbaar te zijn voor open sites? Hoe gaan we dit doen?

**Comment by jfaasen** [comment]
Samenhang met #207. Gaan we over na denken en komen we op terug.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#178
