### ISSUE TITLE
CMS: aangemaakte pagina's niet meer zichtbaar

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#161]
https://intrana.odc.pleio.nl/cms zijn wel pagina's aangemaakt maar die zie je niet meer in overzicht.

**Comment by jfaasen** [comment]
https://kia.pleio.nl/cms/view/55793299/informatie-achiefinstellingen-op-twitter
Lijkt ook verdwenen en niet meer te werken. Staat ook niet meer tussen CMS overzicht.  Enig idee?

**Comment by bartjkdp** [comment]
Lijkt voor nu opgelost.
