### ISSUE TITLE
CMS: Artikelen met tag widget toevoegen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#163]

**Comment by jfaasen** [comment]
Misschien handig om hier de partijen die een intranet op het nieuwe template willen bij te betrekken zodat de widget gelijk aan alle wensen kan voldoen.

**Comment by FabianBui** [comment]
@bartjkdp ik heb de optie Cards toegevoegd met daarin het edit scherm uitgewerkt. Zet 'm door naar jou (cards staat als comment bij otherWidgets in Widget.jsx)

![screen shot 2018-03-21 at 12 49 39](https://user-images.githubusercontent.com/5603405/37708285-57d9f462-2d06-11e8-94b8-56ba1bca6885.png)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#180
