### ISSUE TITLE
Wiki: sub-sub pagina's toevoegen en verslepen/verplaatsen van pagina's [6]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#164]
je kunt wel een sub-sub pagina's aanmaken maar hij plaatst ze dan een niveau hoger als sub pagina en niet op de plek waar de pagina hoort. Graag oplossen. Overigens zijn oude sub-sub items nog niet mee gemigreerd. Zie ook lopende ticket.

**Comment by bartjkdp** [comment]
Er is nog geen ondersteuning voor sub-sub pagina's.

**Comment by jfaasen** [comment]
In ontwerp van Osage zat dit wel inclusief verplaatsen van pagina's. Moet sowiso terugkomen om minimaal te voldoen aan wat de functie was. Wil je inschatting maken?

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#181
