### ISSUE TITLE
Refactoren van huidige CSS code

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#165]
De huidige CSS code is niet altijd modulair opgezet. Het zou mooi zijn als we de code even verder refactoren.

**Comment by bartjkdp** [comment]
We zijn begonnen met het refactoren en het isoleren van generieke componenten in het [Pleio design system](https://www.github.com/Pleio/design-system)

**Comment by MeneerFab** [comment]
We maken hier aparte kaarten voor aan in [Pleio design system](https://github.com/Pleio/design-system)
