### ISSUE TITLE
in IE 11 ziet de CMS pagina's er niet uit

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#166]
De pleio site voor common ground lijkt op IE 11 een beetje brak te zijn. Waarschijnlijk wordt het onderstaande veroorzaakt door een bepaalde manier gebruik van frames. In Chrome gaat het verder goed.
![image002](https://user-images.githubusercontent.com/1875858/36411918-119818b2-1618-11e8-9214-400101c2225c.jpg)

**Comment by bartjkdp** [comment]
@MeneerFab hier heb ik echt jouw expertise bij nodig. Zou je eens kunnen kijken wat hier gebeurt?
https://commonground.pleio.nl/cms/view/54475518/organisatie-common-ground

Het probleem is dus alleen op IE11

**Comment by MeneerFab** [comment]
Opgelost! :)
