### ISSUE TITLE
Statusupdate: Editoropties invoegen uitbreiden [3]

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#167]
In een discussie en blogs kan je bij het plusje allerlei soorten content toevoegen, dat is super (afbeelding, bestand,  video en social media).
bij een statusupdate kan dat niet. Ik zie het nu gebeuren dat iemand (particulier archieven platform) een bestand aanbied van een tweet. Dat vind ik wel zonde, want beter en mooier is om een social media post mooi te kunnen invoegen.

**Comment by jfaasen** [comment]
Kortweg, zelfde editor opties toevoegen als bij editor van blog en discussie

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#182
