### ISSUE TITLE
Admin: verslepen van admin pagina's gaat nog niet goed

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#169]
Probleem met het verslepen van CMS pagina's in het admin pannel heeft toch nog kuren. Titels worden overschreven en url's aangepast.

**Comment by bartjkdp** [comment]
Ik kan het reproduceren, is inderdaad een bug.

**Comment by bartjkdp** [comment]
Dit probleem is opgelost in nieuwere versies.

**Comment by jfaasen** [comment]
Gestest in Firefox en IE en werkt, in IE zit nog wel het gekke verspring ding #112
