### ISSUE TITLE
Profielen: namen in ledenoverzicht groep aanklikbaar maken en doorverwijzen profiel [1]

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#171]
als je op de leden klinkt in een platform/groep, dan zie je de lijst. Het zou mooi zijn dat als je op de namen/profielfoto klinkt je direct doorgeleid wordt naar het profiel van die persoon.

![image](https://user-images.githubusercontent.com/34913358/36670936-33b3ddaa-1afa-11e8-8d71-e749eb2eac7b.png)

**Comment by violetmeerdink** [comment]
Top bedankt!

**Comment by dickmers** [comment]
Is dit al live? Op onze site zijn de namen in de ledenlijst nog niet gelinkt.

**Comment by bartjkdp** [comment]
Nog niet, gaat in de volgende release mee.

**Comment by dickmers** [comment]
super dank je!
