### ISSUE TITLE
Activiteiten: discussies worden niet getoond in de stroom

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#172]

**Comment by jfaasen** [comment]
Zie onderstaand voorbeeld, geldt voor meer groepen. Graag uitzoeken en oplossen: 

![afbeelding](https://user-images.githubusercontent.com/34096240/36730328-54b6d61a-1bc7-11e8-90c9-fd60c3a7910b.png)

**Comment by bartjkdp** [comment]
Het lijkt erop alsof discussies niet worden meegenomen in het activiteitenoverzicht. Dat moet even opgelost worden.

**Comment by bartjkdp** [comment]
Dit is opgelost in e869743

**Comment by jfaasen** [comment]
Discussies weer zichtbaar op groepshomepage, fijn! Sluiten
