### ISSUE TITLE
Registeren: mogelijk maken om verplichte velden uit te vragen [4]

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#173]
Dit is gewenst omdat we in de statistieken willen zie wie waar werkt.

**Comment by jfaasen** [comment]
@bartjkdp ik ben even kwijt. Dit kan nu toch al met het huidige registratieformulier of kan dat niet meer in combinatie met template/database?

**Comment by bartjkdp** [comment]
Op het moment dat je een besloten site hebt, krijg je inderdaad gewoon verplichte profielvelden. Op het moment dat je een open site hebt worden verplichte profielvelden nog niet uitgevraagd op het moment dat je inlogt op de site.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#184
