### ISSUE TITLE
CMS: Sub-sub items toe kunnen voegen, overzicht op alfabet

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#174]

**Comment by jfaasen** [comment]
- [ ] bij /cms volgorde op alfabet

- [ ] bij aangemaakt item, inclusief sub-item volgorde kunnen wijzigen (slepen). En automatisch op alfabet (nu staat laatst gemaakte item bovenaan)

- [ ] sub-sub items kunnen maken

**Comment by jfaasen** [comment]
@bartjkdp deze hangt natuurlijk samen met CMS aan voorkant. Maar ik denk dat als het opgelost wordt onder /CMS het belangrijkste is. Aan de voorkant is dan mooie toevoeging. Straks even bespreken.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#185
