### ISSUE TITLE
Consistentie van het discussie-icoontje [0,25]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#176]
Mensen vinden het verwarrend dat het icoontje van reactie altijd gevuld is, zowel met als zonder reacties is het gevuld. Dit lijkt een beetje anders te werken dan bij likes. @MeneerFab heb jij een idee?

![image](https://user-images.githubusercontent.com/5213690/36898613-e5fe9d96-1e1b-11e8-841b-b41eec6df784.png)

**Comment by jfaasen** [comment]
@MeneerFab, zie ook vergelijkbare tickets. Wens om nog even goed te kijken naar alle symbolen en concequentie daarvan. Bel me vooral even als je meer tekst en uitleg nodig hebt.

**Comment by MeneerFab** [comment]
Ik zou het element helemaal weglaten als er geen reacties zijn, eens?

**Comment by jfaasen** [comment]
Hier geldt dus hetzelfde als bij #180 #177 uitwerking is prima zoals bovenstaande alleen grijze kleur dus niet.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#187
