### ISSUE TITLE
Consistentie van het bookmark-icoontje  [0,25]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#177]
Men verwacht een gekleurd lijntje om het bookmarkicoontje, zoals bij likes.

![image](https://user-images.githubusercontent.com/5213690/36898733-4c5f67f0-1e1c-11e8-9d55-8e12fc675d5f.png)

**Comment by jfaasen** [comment]
Zie ook #176

**Comment by jfaasen** [comment]
Zie commentaar bij #180. Juist geen grijs maar kleur

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#188
