### ISSUE TITLE
Likes: grijze hartjes zijn verwarrend  [?]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#180]
In het trending en top bloggers overzicht vinden mensen de grijze hartjes verwarrend omdat het op een andere plek de primaire kleur van de site is. Mensen associeren grijs met inactief.

![image](https://user-images.githubusercontent.com/5213690/36898939-3c332334-1e1d-11e8-8de5-50f5ae0d5db4.png)

**Comment by MeneerFab** [comment]
Heb de hartjes in de andere cards standaard grijs gemaakt en rechtgetrokken met de bookmark knop. Misschien is het nu minder erg dat deze ook grijs is.

Maar ik vraag me af hoeveel waarde het aantal hartjes hier heeft. Alle hartjes van de artikelen worden bij elkaar opgeteld? Wat heeft een gebruiker precies aan dat getal? Misschien is het genoeg dat het in Trending staat.

**Comment by bartjkdp** [comment]
Wat mij betreft mogen de hartjes hier inderdaad weg.

**Comment by MeneerFab** [comment]
Ben ook benieuwd wat die Trending en Aanbevolen sidebars waard zijn (Leraar), wat gebruikers er van vinden. Qua ontwerp blokkeert het 1/3e van de ruimte van het scherm.

**Comment by jfaasen** [comment]
@MeneerFab zie nu dat alle knoppen grijs zijn gemaakt: hartjes, discussies bewaren. Dat was juist niet de bedoelen. Wel dat alles hetzelfde was en werkte maar dan ik secondaire kleur van de site dus in dit geval roze. Hartjes weg bij trending wat mij betreft oke!

**Comment by FabianBui** [comment]
@jfaasen Ik had dat gedaan om 3 staten te kunnen hanteren (nu was er soms geen verschil tussen hover en aangeklikte staat dus wist je niet of je iets nou al geliked had of niet):

- grijs (nog niet geliked/bewaard)
- kleur (hover)
- kleur ingekleurd (actief/geliked/bewaard)

Ik kan het veranderen, maar weet dan niet precies waarnaartoe

**Comment by FabianBui** [comment]
Ik zal het in ieder geval de volgende keer even eerst in beeld uitwerken en in de ticket posten zodat gebruikers in een keer het goede te zien krijgen 🤓

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#190
