### ISSUE TITLE
We willen graag "Lees Meer" toevoegen aan blogs, discussies, statusupdates en agenda-items  [?]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#181]
Met name statusupdates tonen nu heel groot op de homepage. Deze inkorten en uitklapbaar maken.

**Comment by jfaasen** [comment]
Defensie wil dit ook graag bij lange profielvelden. In deze scope meenemen?! Voorstel nu zou zijn om ... ipv letterlijk lees meer te typen. ook ivm internationale sites in de toekomst.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#191
