### ISSUE TITLE
Agenda: betere navigatie-opties in het lijstoverzicht  [?]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#182]
Nu kun je alleen selecteren tussen "Aankomend" en het "Verleden", maar het zou mooi zijn om meteen naar een bepaalde maand te kunnen navigeren.

**Comment by jfaasen** [comment]
Suggestie van christian om kalendertje toe te voegen

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#192
