### ISSUE TITLE
Profiel: bewoordingen bij het profiel compleetheidsmetertje aanpassen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#183]
Mensen vinden de bewoordingen niet echt complimenteus. Misschien woorden gewoon weghalen en alleen visueel laten zien.

![knipsel](https://user-images.githubusercontent.com/34096240/37650623-5b442386-2c2d-11e8-8f52-b9b0076fa516.PNG)

**Comment by jfaasen** [comment]
eens met voorstel, alleen balkje zonder tekst.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#193
