### ISSUE TITLE
Reacties: onderzoeken of we de reacties wellicht willen inklappen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#185]
Dit zou handig kunnen zijn wanneer er veel reacties zijn om het overzicht te bewaren. Inspiratie opdoen bij Facebook.

**Comment by jfaasen** [comment]
@bartjkdp wie moeten hier nog bij betrokken worden of pak je dit tzt met @MeneerFab op?

**Comment by bartjkdp** [comment]
Een eerste voorstel is hier al te bekijken https://design-system.pleio.nl/?selectedKind=Article&selectedStory=News&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#195
