### ISSUE TITLE
Taken: uitbreiden van de functionaliteit [?]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#199]
We zouden graag taken willen uitbreiden met een simpele project-management tool ala Trello.

- [ ] Borden beheren
- [ ] Kolommen beheren
- [ ] Kaarten beheren
- [ ] Kaarten toewijzen aan een of meerdere personen
- [ ] Einddatum van een kaart
- [ ] Detailweergave van de kaart, reacties toevoegen
- [ ] Vinklijstje maken in de kaart
- [ ] Onderzoeken of het mogelijk moet zijn om hele kaarten door te strepen.

**Comment by jfaasen** [comment]
Kunnen jullie hier een ureninschatting voor maken. Bij het Nationaal Archief is sowieso interesse.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#208
