### ISSUE TITLE
Linkjes werken niet

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#205]
Op sommige externe website wordt verwezen naar de kennisplatforms, maar de links werken niet meer. Ik denk dat dit na de overgang naar het nieuwe template is gebeurd. Kunnen wij daar wat aan doen? Of moeten we de webmaster van die website attenderen?

zie bijv. http://www.netwerkdigitaalerfgoed.nl/kennis-en-voorzieningen/digitaal-erfgoed-houdbaar/ 
onder kopje koppelen van kennis:
![image](https://user-images.githubusercontent.com/34913358/37026583-2166b1aa-212f-11e8-9ad9-5c99ce7f1535.png)

**Comment by jfaasen** [comment]
@bartjkdp zelfde issue als hier? #151

**Comment by bartjkdp** [comment]
Dat klopt, we hadden het wel al opgelost voor `/groups/info` maar nog niet voor `/groups/profile` links. Ik heb dit nu ook gefixt, was er toch.

**Comment by jfaasen** [comment]
@violetmeerdink wil jij zit testen en bevestigen? Dank

**Comment by bartjkdp** [comment]
Vergeet niet te wachten tot de volgende release ;) (morgenavond)

**Comment by jfaasen** [comment]
@violetmeerdink heeft getest en werkt.
