### ISSUE TITLE
editor: statusupdate in mobile of op tablet

### ISSUE THREAD

**Issue by WouterBRu** [Pleio/pleio_template#206]
editor: bij een statusupdate: op mobile en tablet niet mogelijk om tekst in te voeren, vraagt direct om bestand toe te voegen  (aanraken van het tekstveld geeft verkeerde functie)

**Comment by jfaasen** [comment]
@WouterBRu zie ook ticket  #128 eventueel combineren en een sluiten?

**Comment by WouterBRu** [comment]
Nee, beschrijving 128 lijkt me anders , het menu zit niet in de weg bij mijn melding. Maar wellicht wel slim om te koppelen, in die zin dat oplossen van 128 wellicht ook deze oplost.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#213
