### ISSUE TITLE
Profielen: beter duidelijk maken met wie profielinformatie gedeeld wordt

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#207]
Het is nu voor gebruikers erg onduidelijk met wie profielinformatie gedeeld wordt wanneer ze extra profielvelden instellen. We zouden graag per profielveld een keuzeoptie willen inbouwen waarmee de gebruiker kan instellen om:

- Het profielveld alleen met gebruikers van de site te delen.
- Het profielveld met iedereen (het internet) te delen.

Wanneer een site open is, vervalt de optie om het profielveld alleen met gebruikers van de site te delen (?). Iedereen kan immers lid worden van de site.

**Comment by bartjkdp** [comment]
Dit is gefixt in Pleio/pleio_template@ba3749d. Je kunt vanaf nu instellen met wie je profielgegevens deelt.

![image](https://user-images.githubusercontent.com/5213690/37662754-0e9512e0-2c58-11e8-9541-5e4c9165172c.png)

**Comment by violetmeerdink** [comment]
Ha @bartjkdp super dat dit al is verwerkt. Wel zou ik graag bij het 'over mij' ook een keuze willen hebben. Dank!

**Comment by ziemerink** [comment]
Opgelost

**Comment by bartjkdp** [comment]
Voor 'over mij' is het nu ook configureerbaar Pleio/pleio_template@ca71da4
