### ISSUE TITLE
Sommige delen van pleio_template niet indexeerbaar maken door Google

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#208]
Het oude Pleio vroeg aan zoekmachines om bepaalde onderdelen van de site niet te indexeren. We willen dit voor het nieuwe Pleio graag ook toevoegen. Het gaat om een robots.txt met de volgende inhoud:

```
User-agent: *
Sitemap: https://<site>/sitemap.xml
Disallow: /profile/
Disallow: /search/
Disallow: /search
Disallow: /tags/
Disallow: /tags
```

**Comment by jfaasen** [comment]
@bartjkdp voor de scope: het gaat toch om een combinatie van het nieuwe template en een site met een eigen database?

**Comment by bartjkdp** [comment]
Klopt

**Comment by bartjkdp** [comment]
Vanaf Pleio/mod_pleio@f82b038 is dit weer configureerbaar onder "Geavanceerde site instellingen". Dit komt overeen met de instellingen die je vroeger ook had op de gezamenlijke omgeving. Wanneer je indexering door zoekmachines toestaat wordt de zoekmachine gevraagd om alles behalve `/profile`, `/search` en `/tags` te indexeren. Als je geen indexering toestaat (standaardinstelling) dan wordt de zoekmachine gevraagd niets te indexeren.

**Comment by ziemerink** [comment]
Is toch opgelost?
