### ISSUE TITLE
E-mailoverzicht: Permissies van objecten in het e-mailoverzicht controleren

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#210]
Het lijkt dat soms objecten getoond worden in het e-mailoverzicht waar de gebruiker toch geen toegang tot heeft. Hier even onderzoeken of dat echt waar is en eventueel oplossen.

**Comment by bartjkdp** [comment]
Dit is opgelost in Pleio/pleio_template@f2bd749

**Comment by jfaasen** [comment]
@bartjkdp, zou je gezien mijn vakantie morgen iemand anders willen vragen het voor je te testen? Dan hoeft het niet te blijven liggen ;-)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#215
