### ISSUE TITLE
Het schakelaartje werkt niet onder Safari

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#211]
Bij klikken blijft het schakelaartje uit.

**Comment by bartjkdp** [comment]
Dit is opgelost in Pleio/pleio_template@77e5df8

**Comment by jfaasen** [comment]
Voor meelezer nu niet duidelijk waarover het gaat. Willen jullie er uitleg bij geven en prio's aan hangen en/of status toevoegen.

**Comment by bartjkdp** [comment]
Het ging erover dat dit schakelaartje niet werkte in Safari

![image](https://user-images.githubusercontent.com/5213690/38090570-516c5788-3363-11e8-9f9c-aaa2c065faf0.png)

Inmiddels is het opgelost.
