### ISSUE TITLE
“Sorry, deze pagina is nu niet beschikbaar. Aanpassen in:

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#213]
“Sorry, deze pagina is nu niet beschikbaar. Aanpassen in:

Ai, het lukt nu niet om de pagina te openen.
Ben je ingelogd? Zo niet, kun je het na inloggen nogmaals proberen?
Het kan ook zijn dat deze pagina is verplaatst of niet meer bestaat.

**Comment by jfaasen** [comment]
@bartjkdp hier hebben we toch eerder naar gekeken? Volgensmij hadden we daarin ook twee varianten gemaakt met juist een toevoeging over inloggen bij pagina's waarvoor dat noodzakelijk was en het niet noemen wanneer het ging om verwijderde content... ik kan het niet meer terugvinden. Ik vind overigens sorry deze pagina is niet beschikbaar wel netter dan ai, het lukt nu niet. Maar leg het anders vooral voor aan twee of drie andere deelsitebeheerders

**Comment by ziemerink** [comment]
Het mooiste is natuurlijk dat de deelsite beheerder dit zelf in kan stellen, of het dan ai of sorry is maakt niet zoveel uit. Er zijn vele mooi voorbeelden van fout pagina's https://www.frankwatching.com/archive/2010/04/14/15-leuke-nederlandse-404-errorpaginas/

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#216
