### ISSUE TITLE
Bij gebruiker mede beheerder maken van de deelsite krijg ik een error 

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#214]
Als ik een gebruiker deelsite beheerder wil maken krijg ik een error:
Oeps! Er is iets fout gegaan.

Call to undefined method ElggObject::move()

Error Object
(
[message:protected] => Call to undefined method ElggObject::move()
[string:Error:private] => Error: Call to undefined method ElggObject::move() in /app/engine/lib/admin.php:658
Stack trace:
#0 /app/engine/lib/elgglib.php(784): elgg_add_admin_widgets('make_admin', 'user', Object(ElggUser))
#1 /app/engine/lib/users.php(228): elgg_trigger_event('make_admin', 'user', Object(ElggUser))
#2 /app/engine/classes/ElggUser.php(217): make_user_admin(54546305)
#3 /app/actions/admin/user/makeadmin.php(18): ElggUser->makeAdmin()
#4 /app/engine/lib/actions.php(97): include('/app/actions/ad...')
#5 /app/engine/handlers/action_handler.php(20): action('admin/user/make...')
#6 {main}
[code:protected] => 0
[file:protected] => /app/engine/lib/admin.php
[line:protected] => 658
[trace:Error:private] => Array
(
[0] => Array
(
[file] => /app/engine/lib/elgglib.php
[line] => 784
[function] => elgg_add_admin_widgets
[args] => Array
(
[0] => make_admin
[1] => user

**Comment by bartjkdp** [comment]
Op welke site is dit?

**Comment by ziemerink** [comment]
https://istrategie.pleio.nl

**Comment by bartjkdp** [comment]
Ik kan het niet reproduceren...

**Comment by ziemerink** [comment]
Opnieuw geprobeerd en nu werkt het wel!
