### ISSUE TITLE
Overgang: verschillen tussen het oude en het nieuwe Pleio

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#216]
- [ ] Foto albums
- [ ] Evenementen
- [ ] Wiki's
- [ ] Statische pagina's

**Comment by bartjkdp** [comment]
Wat betekent dit precies?

**Comment by ziemerink** [comment]
Als je bijvoorbeeld kijkt bij deze site: https://odachterhoek.pleio-test.nl/ is een kopie van https://odachterhoek.pleio.nl/, dan zijn de aanmeldingen in de evenementen en de wiki's; leeg. Terwijl in de oude omgeving er wel degelijk wiki's zijn in de groepen. Met andere woorden hoe gaan we om met alle soorten content bij het overzetten naar het nieuwe template!

**Comment by bartjkdp** [comment]
Ik begrijp het nu, er zijn veel verschillen tussen het oude en het nieuwe Pleio. Ik denk dat je even heel precies moet beschrijven wat je bedoelt. Ik ga puntsgewijs in op je opmerkingen:

- Fotoalbums: dat klopt, het nieuwe template heeft geen aparte fotoalbums meer. Dit is onderdeel van bestanden geworden. Hier wordt voor nu geen migratiepad voor aangeboden.
- Evenementen: het is onduidelijk wat je hierbij bedoelt. Zowel evenementen als aanmeldingen worden gemigreerd. Ik zie ze ook terug.
- Wiki's: In principe worden alle wikipagina's gemigreerd, alleen is er in het nieuwe template nog geen ondersteuning voor sub-sub-sub niveau's en dieper. Hiervoor is ticket #164 aangemaakt.
- Statische pagina's: Deze kun je in principe terugvinden in het CMS via `/cms`.

**Comment by ziemerink** [comment]
Hier staan twee wiki's die ik niet terug zie in het nieuwe template:
https://odachterhoek.pleio.nl/pages/group/22845832/all

**Comment by bartjkdp** [comment]
En de rest?

**Comment by jfaasen** [comment]
Toevoeging: CMS worden subpagina;s ook nog niet meegenomen. Staat ook ticket voor #174 

Voor andere meelezers zie ook:
https://help.pleio.nl/index.php?title=Het_nieuwe_(responsieve)_Pleio_template
https://help.pleio.nl/index.php?title=Totaaloverzicht

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#217
