### ISSUE TITLE
Ontwikkelen van een verjaardagen widget en profielveld [32]

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#217]
Hoeveel uur kost het om de Birthdays plug-in geschikt te maken voor het nieuwe template: 

- Kunnen zien wanneer een gebruiker jarig is aan de hand van zijn geboorte datum die hij in het profiel heeft ingevuld. Gebruiker bepaald zelf of hij zijn leeftijd wel of niet wil tonen.
- Liefst instelbaar welke periode te tonen XX aantal dagen terug xx aantal dagen vooruit

**Comment by bartjkdp** [comment]
Ik heb een inschatting toegevoegd. Dit is

- UI/UX en HTML/CSS: 16 uur
- Beter profielveld management: 8 uur
- Configureerbare widget: 8 uur

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#218
