### ISSUE TITLE
Overgang: wikipagina's worden niet goed meegenomen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#218]
Zie bijvoorbeeld:

`https://odachterhoek.pleio.nl/pages/group/22845832/all`

en 

`https://odachterhoek.pleio-test.nl/`

**Comment by jfaasen** [comment]
En samenhang met deze #164

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#219
