### ISSUE TITLE
Opslaan data in profiel pagina werkt niet

### ISSUE THREAD

**Issue by dickmers** [Pleio/pleio_template#221]
Bij het wijzigen van een profiel wordt de data niet opgeslagen.
Bv in mijn profiel https://intranet.cultureelerfgoed.nl/profile/dick6 vul ik onder Functie 'webmaster' in, <enter> en het lijkt in orde maar na verversen is de data weer weg. 
Browser: 
- Google Chrome / Versie 65.0.3325.181
- IE 11.0.9900

**Comment by dickmers** [comment]
wellicht hetzelfde als #158 ?

**Comment by bartjkdp** [comment]
Klopt, is een duplicaat van #158. Laten we daar de discussie verder voeren.
