### ISSUE TITLE
profielen / medewerker overzicht

### ISSUE THREAD

**Issue by dickmers** [Pleio/pleio_template#224]
Het lijkt ons heel handig een overzicht te hebben van alle profielen/gebruikers op het intranet. Dan kunnen mensen daar vinden hoe ze mensen kunnen  bereiken, wat hun expertise is, etc. 
We stellen ons functionaliteit voor zoals /news, /agenda, /questions, maar dan /profiles met een lijst, zoeken en filteren, plus een widget-toepassing om het in een campagne pagina te kunnen zetten. 

Opm van @ziemerink : Is een wens van meerdere organisaties oa VWS en RVO.

**Comment by bartjkdp** [comment]
Dit is volgens mij een duplicaat van #99

**Comment by dickmers** [comment]
OK!
Hier heet het ledenoverzicht, ik zocht op profiel/medewerkers...

**Comment by bartjkdp** [comment]
Geen probleem 👍
