### ISSUE TITLE
aanvang- en eindtijd van een event in Agenda 

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#225]
Hierbij een verzoek tot een kleine aanpassing van de KIA template.

Bij het maken van een Evenement kan ik de aanvang- en eindtijd van een evenement aangeven. Dit gebeurt d.m.v. een drop down menu waarbij de tijden zijn voor gedefinieerd in hele en halve uren. Het is echter niet mogelijk om bijvoorbeeld een evenement om 8.45 uur te laten beginnen. Het zou wenselijk zijn om de voor gedefinieerde lijst uit te breiden of het mogelijk te maken om vrije tekst in te voeren.

Onderstaand een printscreen. N.b.: de tijd die je nu in de prinscreen ziet staan is het tijdstip waarop ik deze maakte en niet door mij ingevoerd.
Jeroen Padmos - aanjager openbaarheid
![image](https://user-images.githubusercontent.com/34913358/38498330-5f1f7528-3c04-11e8-8f52-e55e96100b4a.png)

**Comment by dickmers** [comment]
klopt, net als #222

**Comment by bartjkdp** [comment]
Deze wens staat genoteerd in #222, deze zal ik voor nu sluiten.
