### ISSUE TITLE
IE bug: plaatje in cms pagina schaalt niet 

### ISSUE THREAD

**Issue by dickmers** [Pleio/pleio_template#227]
Op CMS pagina's worden afbeeldingen in tekst blokjes niet goed geschaalt, ze krijgen hun orginele formaat en schuiven daardoor uit de kolommen.
bv op https://intranet.cultureelerfgoed.nl/cms/view/56122603/organisatie
Met een beetje extra custom css heb ik het opgelost.
`.DraftEditor-root img {
	width: 100%;
}`

**Comment by dickmers** [comment]
![screenshot intranet](https://user-images.githubusercontent.com/37140479/38976363-717c9f34-43b1-11e8-817b-129dc4937060.JPG)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#224
