### ISSUE TITLE
insert hyperlink, voorkomen van https://https://...

### ISSUE THREAD

**Issue by dickmers** [Pleio/pleio_template#228]
Bij het invoegen van een hyperlink blijft in het venstertje "Hyperlink toevoegen" het stukje https:// staan. Gebruikers plakken hun gekopieerde url hier achter zodat er https://https://... komt te staan en de hyperlink dood loopt.

Beste lijkt me dat het veldje na select/focus leeg wordt gemaakt, om dit te voorkomen.

Misschien is het nog mooier relatieve links te maken, maar dat is wellicht een stuk ingewikkelder.

**Comment by jfaasen** [comment]
samenhang met #209 wellicht in een keer op te pakken.

**Comment by dickmers** [comment]
klopt goed idee

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#225
