### ISSUE TITLE
Profiel: Andere social media koppelen

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#23]

**Comment by SaskiavdM** [comment]
1. Het is nu niet mogelijk om je profielgegevens privé/publiek te zetten. Je zet al je gegevens d.m.v. één schuifje privé of publiek. 
2. Publiek = toegangsniveau deelsite
3. Locatie en organisatie horen in het bovenste blok
4. Als je in het onderste blok (Over mij) iets invult, is dat altijd op toegangsniveau deelsite 
5. In het onderste blok komen ook links voor 'twitter' en 'linkedin'
6. Als je een deel van de gegevens in het bovenste blok niet openbaar wil zetten, maar de rest wel: niet openbare gegevens niet invullen.

NB: toegangsniveau deelsite openbaar: zonder inloggen toegankelijk en door google indexeerbaar.

**Comment by bartjkdp** [comment]
Na wat uitproberen met schuifjes en zo heb ik gezien dat het toepassen van die schuifjes eigenlijk helemaal niet nodig is.

De reden dat we een instelling zoeken is vanwege het veld "e-mailadres", deze geef je op tijdens registratie en wil je niet persé delen met andere leden. Alle andere velden zijn niet verplicht en geeft een gebruiker dus volgens mij ook gewoon niet op wanneer hij ze niet met andere personen wil delen.

Ik heb het nu zo gemaakt dat het veld e-mailadres standaard niet met anderen gedeeld wordt. Op het moment dat je het wel wil delen, wijzig je het e-mailadres en staat standaard het juiste adres ingevuld. Op het moment van opslaan wordt het veld gedeeld met andere gebruikers. Bij verwijderen wordt het veld weer grijs (en deel je het dus niet meer met anderen).

**Comment by bartjkdp** [comment]
De velden locatie en organisatie heb ik voor nu besloten om toch beneden te laten, dit zijn voor nu site-specifieke velden en komen daarom beneden.

**Comment by bartjkdp** [comment]
In plaats van het invulveld e-mail is er een schuifje gekomen waarmee je het permissie-niveau instelt vanaf e3f188e.

**Comment by bartjkdp** [comment]
Ik zit te klooien met de social media velden. Ik wil heel graag dat er iets voor komt, maar ik denk dat het nog wat ontwerpwerk is. Niet heel veel (heel weinig denk ik), maar het moet wel even gebeuren. Wat zullen we doen?

**Comment by ziemerink** [comment]
Ik zeg OSAE vragen!

**Comment by jfaasen** [comment]
@ziemerink kan dat vanuit Pleio? Anders label zoek financiering?

**Comment by ziemerink** [comment]
Wij hebben nu geen strippenkaart met OSAGE, dan zullen we eerst een offerte moeten hebben deze even langs het bestuur maar dat is een formaliteit. Dus op zich geen probleem, maar als er een snellere weg is lijkt mij dat beter!

**Comment by jfaasen** [comment]
Samenhang met profielen is te vinden in #208.

**Comment by bartjkdp** [comment]
Dit kan Fabian denk ik nu zelf oppakken

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#145
