### ISSUE TITLE
1 telefoonveld maken

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#24]

**Comment by bartjkdp** [comment]
Besloten om toch niet op te lossen. Andere organisaties willen graag twee velden hebben.

**Comment by jfaasen** [comment]
Voorkeur vanuit KIA en Pleio is om het terug te brengen naar een veld. ivm helder profiel. Bart bespreekt met Leraar.nl en Junissa vraagt RVO of ze het daar mee eens zijn.

**Comment by jfaasen** [comment]
@bartjkdp , Jose vond het prima. Wat mij betreft kunnen we dit dus afronden.
