### ISSUE TITLE
Vragen en taken standaard uit in groep

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#28]

**Comment by bartjkdp** [comment]
Opgelost in 261b326

**Comment by jfaasen** [comment]
Werkt beiden maar Vragen heet nu Forum. Dit moet nog gewijzigd worden in 'vragen'. Daarmee kan dan straks ook makkelijke overgestapt (en gemigreerd worden). Pas als FFD overstapt dan moet de naam eventueel aanpasbaar worden?
