### ISSUE TITLE
Vragen: uitbreiden van functionaliteit

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#29]
- [x] Vinkje "dit is het juiste antwoord" toevoegen.
- [x] Mogelijkheid toevoegen om expert-rollen toe te voegen.
- [x] Experts hebben de mogelijkheid om het vinkje "dit is het juiste antwoord" te kiezen.

**Comment by jfaasen** [comment]
Status: voor sites die nu overgaan en gebruik maken van Vragen wordt de situatie alsvolgt. Vragen worden gemigreerd maar Vinkje verdrwijnt. Evenals optie om vragen te sluiten en expert rollen zitten er nog niet in. Bart brengt in januari RVO en NA bij elkaar om deze functie verder door te ontwikkelen. En bovenstaande checklist aan te vullen.

**Comment by bartjkdp** [comment]
Deze functionaliteit is weer toegevoegd aan vragen. Je kunt nu weer expertrollen beheren in het beheerpaneel en experts kunnen het juiste antwoord aanvinken.
