### ISSUE TITLE
Beheerpaneel: welkomsbericht site toevoegen [2]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#30]
We willen graag een functie toevoegen in het beheerpaneel waarmee een beheerder een welkomsbericht kan instellen. Nieuwe leden ontvangen dit bericht per mail.

**Comment by bartjkdp** [comment]
Toegevoegd

![image](https://user-images.githubusercontent.com/5213690/33934344-ea73e018-dff8-11e7-9704-18ac1e0f934f.png)

**Comment by jfaasen** [comment]
bespreken met Violet ivm i in groep

**Comment by ziemerink** [comment]
Kan toch zoals nu ook is? Instelbaar door de beheerder van de groep. Ik zou deze functie ook graag willen voor de deelsite.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#146
