### ISSUE TITLE
Groep: Subgroepen en autorisatieniveaus toevoegen [6]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#31]

**Comment by bartjkdp** [comment]
Veel werk al gedaan in 492affc. Eerst maar eens testen hoe dit werkt.

**Comment by bartjkdp** [comment]
De mogelijkheid om subgroepen toe te voegen, wijzigen en verwijderen is sinds 3b9d231 toegevoegd.

**Comment by jfaasen** [comment]
Ik heb een aantal test uitgevoerd. Voor zover ik kan beoordelen worden bestaande subgroepen netjes overgenomen. Het delen van een ODT met subgroep werkt evenals bij uploaden. Gebruiker die geen lid is kan het bestand ook niet zien.
indien subgroep lid wel lees  maar geen schijfrechten heeft dan zie je bij schrijfrechten niets staan. Handig om hier 'gelimiteerd' toe te voegen, net als nu? of andere ideeen? Zie hieronder.  

![afbeelding](https://user-images.githubusercontent.com/34096240/35330995-02ecc514-0106-11e8-9ae8-dd85c31c0c08.png)

Het overzicht van leden van een subgroep bij grote groepen is nog niet duidelijk. Ook het toevoegen is hier lastig. Je kunt alleen naam aanpassen maar je wil eigenlijk nog een veld om lezen te kunnen zoeken. Nu moet je de hele lijst doorscrollen. Zou het nog een optie zijn om leden van de subgroep aangevinkt bovenaan te tonen? Zodat je in een oogopslag ziet wie al lis. En daaronder de rest en dan een zoekveld?

**Comment by bartjkdp** [comment]
@jfaasen het beheren van subgroepen is nog niet ideaal, maar zat ook echt niet in oorspronkelijke scope van het project. Voor nu moeten we het wat mij betreft hier mee doen, het is wel functioneel. Om het echt goed te krijgen hebben we wat UI/UX hulp nodig wat mij betreft. Ik wilde zoeken eerst inbouwen, maar dat werd ook heel verwarrend met de subgroepnaam.

**Comment by bartjkdp** [comment]
Er wordt vanaf dbd3201 "Gelimiteerd" getoond wanneer het permissie-niveau niet beschikbaar is.

**Comment by jfaasen** [comment]
Prima. ik zal morgen dbd3201 testen. Daarna zal ik een prio 2 aanmaken voor doorontwikkeling, inclusief UI/UX. (osage dus neem ik aan?)

**Comment by bartjkdp** [comment]
Kan, maar het mag ook iemand anders zijn hoor ;)

**Comment by ziemerink** [comment]
Nu kun je subgroepen niet uitzetten?

**Comment by bartjkdp** [comment]
Ik maak er een site-brede instelling van die je moet aanzetten.

**Comment by bartjkdp** [comment]
Vanaf 415a648 is het configureerbaar op site-niveau.

**Comment by jfaasen** [comment]
werkt
