### ISSUE TITLE
CMS: mogelijk maken van verplaatsen van rijen en blokken in het cms

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#38]

**Comment by jfaasen** [comment]
Is het een idee om een ticket te maken voor het CMS met afvink lijstje? En daarbij de scope te zeggen wat er nu ontworpen is en dus uitgevoerd kan worden. Dan kunnen we goed onderscheiden wat nieuwe wensen zijn. Iedereen heeft belang bij het CMS.

**Comment by bartjkdp** [comment]
Top idee, staat nu in #15
