### ISSUE TITLE
Groep: Eigenaarschap van groep overdragen [2]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#42]

**Comment by bartjkdp** [comment]
Mogelijkheid toegevoegd in a39c3ba

**Comment by jfaasen** [comment]
@bartjkdp kan wel eigenaar kiezen maar je blijft dan zelf ook eigenaar (je hebt dus twee eigenaren) en de nieuwe eigenaar ontvangt geen e-mail melding.

**Comment by bartjkdp** [comment]
Hee Junissa, ik denk dat jij met een oude versie hebt getest. Kun je de pagina even verversen en het nog eens proberen om over te zetten?

**Comment by jfaasen** [comment]
@bartjkdp, Yes, werkt nu prima! moet dus alleen nog een e-mailtje volgen bij overdracht eigenaarschap.

**Comment by bartjkdp** [comment]
Vanaf de volgende release wordt een mailtje aan de nieuwe groepseigenaar gestuurd.

**Comment by jfaasen** [comment]
werkt top! kan gesloten worden

![afbeelding](https://user-images.githubusercontent.com/34096240/35330719-c6dbc418-0104-11e8-84c4-34957fded5e8.png)
