### ISSUE TITLE
Groep: knop lidmaatschap aanvragen bij groepen [2]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#46]
Het is nu nog niet mogelijk om lidmaatschap aan te vragen voor gesloten groepen. Groepsbeheerders kunnen wel leden uitnodigen om lid te worden van de groep. Graag willen we de "lidmaatschap aanvragen" functie ook toevoegen.

**Comment by bartjkdp** [comment]
Je kunt vanaf nu toegang aanvragen tot een groep. fe322b4

**Comment by jfaasen** [comment]
werkt netjes in IE en in Firefox! in safari ook? dan sluiten
