### ISSUE TITLE
Groep: Uitnodigen, afwijzen, opnieuw uitnodigen in groep werkt niet?

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#47]

**Comment by bartjkdp** [comment]
Ik heb het heel uitgebreid getest, maar kan geen problemen vinden. Probeer het nog eens?

**Comment by SaskiavdM** [comment]
E-mailproblemen zijn nog niet opgelost, dit kan nog niet getest worden. Daarom reopenen

**Comment by jfaasen** [comment]
Iemand uitnodigen werkt, zelf accepteren via link in mail ook. Je komt dan gelijk terecht in de groep. 
Overigens als je inlogd en naar de groep gaat wordt je niet herkent/verschijnt er geen scherm. Je ziet ook nergens op de site dat je een uitnodiging hebt openstaan. 
herinnering versturen werkt nog niet
als iemand vrijwillig de groep verlaat kan die daarna niet meer lid worden. omdat herinnering niet werkt en oude mail link ook niet:
![afbeelding](https://user-images.githubusercontent.com/34096240/34434503-eb32e4dc-ec86-11e7-99a0-e4ed342e76f9.png)

**Comment by bartjkdp** [comment]
Volgens mij is dit een gewenst effect. Een uitnodiging kan maar 1x gebruikt worden. Wanneer je een uitnodiging gebruikt, lid-af wordt en opnieuw lid wil worden, dient de groepsbeheerder je opnieuw uit te nodigen.

**Comment by jfaasen** [comment]
Snap ik alleen het opnieuw uitnodigen werkt dus nog niet evenals herinneren.

**Comment by bartjkdp** [comment]
Ik kan het niet reproduceren. Bij mij werkt het echt zoals verwacht.

**Comment by jfaasen** [comment]
Samen naar gekeken, werkt inmiddels. Alleen het refreshen van de lijst moet Bart nog instellen. Daarna sluiten.
