### ISSUE TITLE
Groep: Subselectie maken bij e-mail versturen [4]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#49]
Het zou mooi zijn als je een subselectie kan maken van de personen. Ook een testmail naar jezelf sturen zou heel prettig zijn.

**Comment by bartjkdp** [comment]
Mogelijkheid om testberichten te versturen zijn nu toegevoegd

**Comment by bartjkdp** [comment]
Opgelost in 6267b26

**Comment by jfaasen** [comment]
@bartjkdp: selectie werkt prima in IE en firefox. Je krijgt netjes melding dat die verstuurd is. Testbericht aan jezelf wordt wel verstuurd maar je krijgt geen melding in het scherm. Graag nog toevoegen. Verder is de afzender in alle berichten nog Pleio. Dit moet de site zijn. Nog aanpassen

**Comment by bartjkdp** [comment]
De afzender van het bericht is een ander probleem, dit heb ik gemeld in #111 (en opgelost). Vanaf de volgende release komt er ook een melding dat het bericht is verstuurd.

**Comment by jfaasen** [comment]
@bartjkdp e-mail versturen in IE blijft hangen. refreshen werkt ook niet. Firefox werkt wel prima
![afbeelding](https://user-images.githubusercontent.com/34096240/35327567-32e8f276-00fa-11e8-95c0-b439cf743ff8.png)

**Comment by bartjkdp** [comment]
Dit zou nu opgelost moeten zijn bf17944. Komt vanavond online.

**Comment by jfaasen** [comment]
@bartjkdp Blijft nogsteeds hangen

**Comment by bartjkdp** [comment]
Hmm was inderdaad nog wat gedoe onder IE. Nu (eb0861c) zou het dan toch écht opgelost moeten zijn.
