### ISSUE TITLE
Tags: Standaardtags definieren

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#50]
Wellicht gewoon een dynamisch systeem dat zich aanpast

**Comment by jfaasen** [comment]
- [ ] standaard tags in groepen ( in oude template bij groep bewerken, tweede tabblad)
- [ ] tags op deelsite niveau in admin

bespreken evenals samenhang met categorieen e.d.

**Comment by ziemerink** [comment]
Als groepen en content inclusief document goed doorzoekbaar zijn is dit niet meer nodig in mijn ogen!

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#150
