### ISSUE TITLE
Groep: Kiezen om een activiteit te genereren bij vernieuwen content

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#51]

**Comment by jfaasen** [comment]
Bij overschrijven van document is soms een statusupdate gewenst evenals bij aanpassen evenementen. Voorstel standaard uit maar keuze knop om update te melden.

**Comment by bartjkdp** [comment]
Wat nu wel een mooie flow is (en hoe ik mensen ook al in de praktijk heb zien werken) is dat je gewoon files upload, en als je dan mensen wil attenderen, dat je gewoon een statusupdate plaatst. Volgens mij kan dat ook best goed werken?

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#151
