### ISSUE TITLE
Pagina's: nadenken over hoe statische pagina's terugkomen in het nieuwe template

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#53]
Statische pagina's op hoofdniveau -> CMS pagina's
Statische pagina's voor groepen -> Wiki pagina's?

**Comment by bartjkdp** [comment]
Site faculteitmilitairewetenschappen.pleio.nl als testsite gebruiken.

**Comment by bartjkdp** [comment]
Statische pagina's komen nu terug in het CMS onder /cms

**Comment by jfaasen** [comment]
Hier Prio 2 voor maken (moderatie rechten en verdere doorontwikkeling van subitems en subsubitems? En samenhang wiki in groepen)
 en zoek financiering label?
