### ISSUE TITLE
CMS: Menu-items beheren vanuit de site en mogelijkheid om subitems aan te maken.

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#54]
Werkt nu nog vanuit de plugin-instellingen.

- [ ] Mogelijkheid om volgordes te bepalen met behulp van drag & drop.
- [ ] Aanmaken van pagina's
- [ ] Mogelijkheid om subitems aan te maken.
- [ ] Mogelijkheid om permissies in te stellen per item.

**Comment by jfaasen** [comment]
Pagina's aanmaken maar ook toevoegen aan menu en menu aanpassen aan de voorkant. En afstemmen wat er dan nog aan de achterkant overblijft.

**Comment by jfaasen** [comment]
beginnersfoutje

**Comment by jfaasen** [comment]
De links die zijn aangemaakt blijven nu niet staan in het admin pannel voor andere beheerders zichtbaar: 

dit zie ik: 
![afbeelding](https://user-images.githubusercontent.com/34096240/34945979-5f875346-fa05-11e7-84cf-bee247b1067e.png)

Dit ziet Sandra:

![afbeelding](https://user-images.githubusercontent.com/34096240/34945903-26e6d3ae-fa05-11e7-9ead-ce3af56feec5.png)

Als zij iets wil toevoegen verdwijnt alles. Lijkt me niet de bedoeling!

**Comment by bartjkdp** [comment]
Dit is volgens mij een losse bug. Het beheerpaneel werkt nog niet goed onder IE.

**Comment by bartjkdp** [comment]
Staat genoteerd in #93

**Comment by jfaasen** [comment]
@bartjkdp even kijken naar samenhang met #15 #174 eventueel samenvoegen en sluiten

**Comment by bartjkdp** [comment]
We twijfelen of we een submenu-functionaliteit moeten toevoegen. Op veel plekken waar de submenu-functionaliteit gebruikt wordt, wordt de site ook snel zo complex dat deze niet meer goed te navigeren is. 

Het intranet van RVO of VWSnet is een goed voorbeeld. Naar onze mening worden daar te veel opties geboden in het menu, waardoor de gebruiker de weg kwijt raakt. Een alternatieve constructie om toch subitems aan te bieden kan gerealiseerd worden op de manier zoals [bij KIA](https://kia.pleio.nl/cms/view/52664862/over-kia).

![image](https://user-images.githubusercontent.com/5213690/38549903-68f2bd10-3cb5-11e8-85ee-becb5ac42e37.png)

Dit houdt het hoofdmenu eenvoudig en staat toch een complexere informatiestructuur toe.

**Comment by ziemerink** [comment]
Nee dit is echt essentieel, je wilt niet op alle pagina;s zo'm lelijk menu aan de linker kant waar door je een enorme lege witte ruimte krijgt onder het menu! Je hoeft het niet te gebruiken! Is natuurlijk een keuze!

**Comment by bartjkdp** [comment]
Overigens vind ik dit een goed voorbeeld van gebruik van het submenu:

![image](https://user-images.githubusercontent.com/5213690/38606964-c67795b0-3d77-11e8-99d9-4252caa24322.png)

**Comment by ziemerink** [comment]
Je bedoelt het pijltje naast Thema?

**Comment by bartjkdp** [comment]
Jep, hier voegt het submenu wel degelijk wat toe ;)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#152
