### ISSUE TITLE
Wiki opzetten voor help.pleio.nl

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#55]

**Comment by jfaasen** [comment]
Ik zou dit pas oppakken na overleg bestuur, communicatie in samenhang met nieuwe home, inrichting helpdesk. en dan ook kijken wat er met mijndeelsite moet.

**Comment by ziemerink** [comment]
We zijn al bezig, daarmee kunnen we nu al alles op een plek documenteren. Daarnaast kunnen we hier ook direct alle instructie oor het nieuwe template bijhouden. Later zetten we alle andere in info daar waar relevant over.

**Comment by bartjkdp** [comment]
Dit is gerealiseerd op https://help.pleio.nl
