### ISSUE TITLE
Zoeken: Zichtbaarheid van zoekveld vergroten [0.5]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#56]
- [x] Er is een CSS bug op Safari
- [x] Graag hoger contrast door echt invul-veldje te maken (witte achtergrond)

**Comment by jfaasen** [comment]
Zowel in menubalk op hoofdniveau als in groepsniveau

**Comment by bartjkdp** [comment]
Opgelost in a647523

**Comment by bartjkdp** [comment]
Er is een CSS bug op Safari

**Comment by bartjkdp** [comment]
Beiden weer opgelost in a78c6ae

**Comment by jfaasen** [comment]
Getest op Energieslag en KIA in IE en Chrome. Ziet er netjes uit. Kleur vergrootglas hoofdniveau wordt aangepast naar site. Veld wit of binnen groep lichte tint van groepsveld.  Afgerond kan gesloten worden.
