### ISSUE TITLE
Profiel: organisatieveld maken [0.5]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#57]

**Comment by bartjkdp** [comment]
Dit is configureerbaar in het template, zie: https://kia.odc.pleio.nl/admin/plugin_settings/pleio_template. Ik heb ze al toegevoegd op KIA test, zie: https://kia.odc.pleio.nl/profile/bartjeu

**Comment by ziemerink** [comment]
De profielvelden worden omgekeerd weergegeven:
Aangemaakt in volgende
1
2
3

Weergave
3
2
1

Voor de beheerder is dit erg verwarrend!

**Comment by bartjkdp** [comment]
Goed punt, ik fix het even!

**Comment by bartjkdp** [comment]
Opgelost in fda299d

**Comment by SaskiavdM** [comment]
Aangemaakt, nog wel aanpassen. Staat verwerkt in comment #23
