### ISSUE TITLE
Nieuws aanpassen in Inspiratie.

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#59]
Kun je op deze pagina het woord Nieuws vervangen door Inspiratie?

**Comment by bartjkdp** [comment]
Op welke pagina? Ik snap het niet helemaal.

**Comment by ziemerink** [comment]
Hier: 
<img width="660" alt="schermafbeelding_2017-12-01_om_15_00_47" src="https://user-images.githubusercontent.com/1875858/33485952-979cf75c-d6a8-11e7-97ab-8f6288c91b91.png">

**Comment by bartjkdp** [comment]
Ahzo. Dit is (helemaal) niet makkelijk te realiseren nu. In de nieuwe backend kan dit wel.
