### ISSUE TITLE
Editor: Integratie van groepsbestanden verbeteren [2]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#6]
- [x] Documenten hernoemen naar bestanden.
- [x] Bestaande bestanden van een groep kunnen toevoegen.
- [ ] Als je bestanden upload in een groep, plaats je ze ook binnen de groep.

**Comment by bartjkdp** [comment]
Het laatste punt is erg lastig om op te lossen en kan ik nu helaas niet meer meenemen. Misschien iets voor prio 3.

**Comment by SaskiavdM** [comment]
Documenten invoegen in groepsactiviteitenstroom

- [ ] In de pop-up eerst terechtkomen in de bestandenstructuur van de groep, zodat gebruikers duidelijk zien dat bestanden niet nieuw hoeven toevoegen

- [ ] Selecteren vervangen door 'vanuit groepsbestanden'

- [ ] Het andere tabblad blijft 'uploaden'

**Comment by bartjkdp** [comment]
Ik heb het tabblad hernoemd. Ik heb toch (voor consistentie) besloten om het tabblad uploaden eerst te tonen.

**Comment by jfaasen** [comment]
Werkt!
