### ISSUE TITLE
CMS: Wikipagina aanmaken hoe kleuren e.d.  in het admin werken om huisstijl te kunnen maken [0.5]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#60]
Zoals net besproken het aanmaken van een uitlegpagina hoe deze onderdelen werken.

Hoi Bart, wil je bij deze sites checken waarom de kleuren in het schema niet werkt (worden anders gemengd en tekststandaard zwart ipv wit). Verder ziet Sandra binnen haar werkomgeving de kleuren niet in het admin en ik wel.

**Comment by bartjkdp** [comment]
Ik zie dat de kleuren wel werken. Het is wel goed om te beseffen dat je "basiskleuren" selecteert. Op basis van de basiskleuren worden allerlei varianten door de CSS zelf gegenereerd en vallen bijvoorbeeld kleuren in het menu lichter of donkerder uit. Misschien gebruikt Sandra een oude browser?

**Comment by jfaasen** [comment]
ze werkt met IE 10 maar wel iets om rekening mee te houden. Blenden snap ik nog niet helemaal want ook bij standaard rijkshuisstijlkleuren zit er verschil in. om nog even nader te bespreken.

**Comment by bartjkdp** [comment]
Gedocumenteerd in https://help.pleio.nl/index.php?title=Mijn_eigen_stijl_instellen
