### ISSUE TITLE
Admin: menu-items in adminpagina kunnen veranderen van volgorde

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#61]
Je kunt nu aangemaakte menuitems nog niet veranderen in volgorde. Dit is wel nodig

**Comment by ziemerink** [comment]
Je kunt het wel veranderen, maar niet slepen. Als je nu namelijk onder een leeg veld aanmaken en vervolgen de volgorde wijzigen. Als het veel werk is zou ik zeggen prio 2.

**Comment by bartjkdp** [comment]
Het is nog wel wat werk om de menu editor die Osage heeft gemaakt te implementeren, dus ik zou zelf zeggen prio 2.

**Comment by bartjkdp** [comment]
Ik ga deze toch sluiten, ik zal het noteren als onderdeel van #54 .
