### ISSUE TITLE
Pagina's: lees-, schijfrechten en moderatie bij CMS-pagina's [16-24]

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#62]
wel over gehad maar ik zag hem niet terug als los punt. scope intraNA

**Comment by bartjkdp** [comment]
Het gaat dan met name om moderatie volgens mij. Lees- en schrijfrechten komen er nu al in.

**Comment by jfaasen** [comment]
@bartjkdp sub sub pagina's kunnen wel aangemaakt worden maar worden niet opgeslagen. Is dit een bug of moet dit ook nog ontwikkeld worden binnen dit punt?

**Comment by jfaasen** [comment]
sitebrede subgroep voor moderatierollen. Zie ook ticket nieuws zoals besproken met Bart

**Comment by jfaasen** [comment]
Samenhang met #54

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#153
