### ISSUE TITLE
Groep: Oneindig scrollen bij groepsleden toevoegen [0.5]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#64]
Dit werkt nu nog niet waardoor je alleen de eerste 10 resultaten ziet

**Comment by bartjkdp** [comment]
Gefixt in c657737

**Comment by bartjkdp** [comment]
Gefixt in c657737

**Comment by jfaasen** [comment]
Bij chrome werkt oneindig scrollen. Zoekfunctie werkt goed en snel Bart!
bij IE zie je dubbele scrollbalk, hij laad ook traag. werkt nog niet goed:

![afbeelding](https://user-images.githubusercontent.com/34096240/34407954-567f5232-ebc1-11e7-9632-99b090e24c1d.png)

**Comment by jfaasen** [comment]
Bij wijzigen van rechten. Onderste persoon zie je verwijderen niet:

![afbeelding](https://user-images.githubusercontent.com/34096240/34408137-5545d052-ebc2-11e7-89a1-62daa426e357.png)
![afbeelding](https://user-images.githubusercontent.com/34096240/34408143-5b0b7b04-ebc2-11e7-88c8-bec731d29571.png)

**Comment by jfaasen** [comment]
@bartjkdp bij kleine groepen in IE is het verdwenen maar bij een grote groep bv helpdesk zie je nog steeds de twee balken en is het doorscrollen lastig. Wil je dit nog controleren? Thanks

**Comment by bartjkdp** [comment]
Oke nu heb ik het echt opgelost in 1a58d56

**Comment by jfaasen** [comment]
Yes, kan gesloten worden
