### ISSUE TITLE
Video: uitwerken met RVO NA FFD hoe video's terug te brengen

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#65]
De oude video functie verdwijnt. Bij FFD is al een voorzet gedaan. Overleg tot ontwikkeling met bovengenoemde partijen.
Belang NA is videotheek van Archief 2.0. te kunnen migreren

**Comment by ziemerink** [comment]
Ik haak graag aan!

**Comment by jfaasen** [comment]
ook reactieveld vereist voor KIA (overname video's Archief 2.0)

**Comment by bartjkdp** [comment]
Duplicaat van #153
