### ISSUE TITLE
Beheerpaneel: Automatisch lid worden van een groep bij lid worden van een site [1]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#7]

**Comment by bartjkdp** [comment]
Oplossen /admin/plugin_settings/group_tools

**Comment by bartjkdp** [comment]
Dit is op de genoemde locatie beschikbaar vanaf Pleio/group_tools@b1aadb3

**Comment by jfaasen** [comment]
Werkt bij bovengenoemde url en dan-> groepen met speciale status -> tweede tabblad
![afbeelding](https://user-images.githubusercontent.com/34096240/35471946-f657b540-0365-11e8-94bb-9bbc6005bf2f.png)

**Comment by jfaasen** [comment]
yes, werkt nu. Ik merk nu wel dat ingelogd groepen heel traag laden en er af en toe dubbele menu items laat zien. Op twee pc's getest met twee accounts:

**Comment by bartjkdp** [comment]
Heb dubbele menu hoort zo. Help staat zowel in groepen, maar valt ook onder Help.

**Comment by jfaasen** [comment]
@bartjkdp ik snap dat ze technisch onder twee plaatsten staan maar het is gek dat als je op een menu item klikt een ander menu oplicht toch? Is nergens anders zo.

**Comment by ziemerink** [comment]
Waar stel je nu in dat iedereen automatisch lid moet worden van een groep? Ik zie wel waar ik het kan verwijderen!

**Comment by bartjkdp** [comment]
Discussie over menu gisteren toegelicht, gaat niet over dit ticket. Functie voor groepen werkt.
