### ISSUE TITLE
Agenda: foto toevoegen mogelijk maken in de groepen

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#72]
op hoofdniveau een blokje (foto) uit de aangemaakte groepen laten zien

**Comment by jfaasen** [comment]
Toelichting: bij Agenda items op hoofdniveau kun je een omslagfoto kiezen. In groepen straks ook. hier wordt een kleinere foto uit gemaakt voor in het overzicht i.v.m groepsstyling. Op hoofdniveau in de lijst en op groepsniveau worden daarmee alle agenda items gelijk uitgelijnd. In alle gevallen zie je een blauw blokje als er geen foto is ingevuld.

**Comment by bartjkdp** [comment]
Opgelost in 04b041f

**Comment by jfaasen** [comment]
@bartjkdp ik zie nogsteeds in een groep geen optie om foto toe te voegen zoals op hoofdniveau dus kan dit niet testen.

**Comment by bartjkdp** [comment]
@jfaasen dit komt vanavond online

**Comment by jfaasen** [comment]
Firefox en IE werkt. Als jij safari hebt getest kan hij gesloten worden.

**Comment by bartjkdp** [comment]
Werkt ook!
