### ISSUE TITLE
Stijling problemen in IE

### ISSUE THREAD

**Issue by violetmeerdink** [Pleio/pleio_template#73]
CSS bugs

- [ ] bij uploaden foto in discussie is de uilijning heel raar, als je naar rechts scrollt..
- [x] uitnodigen leden lukt niet goed, want je ziet niet hele veld (o.a. de 'plus')
- [x] zoekbalk niet mooi uit uitgelijd, plakt aan de bovenrand
- [x] dubbele scrolbar bij leden uitnodigen
- [x] de startpagina valt onder het blokje (ook bij 100% zicht)
- [x] bij discussie starten in een groep, als je een plaatje upload, valt deze heel groot. Na publiceren valt de foto prima.
- [x] beheerknopje uitlijning valt buiten beeld, anders dan in Chrome.
- [x] agenda aanmaken knop valt ook buiten beeld. Alle knoppen even checken

**Comment by bartjkdp** [comment]
Opgelost in 5c83ee7

**Comment by jfaasen** [comment]
@bartjkdp werkt allemaal alleen het onderdeel foto met discussie kon ik niet testen gezien ik niet weet waar dit over ging. Wil jij dit nog even controleren dan kan hij daarna gesloten worden. Thanks!

**Comment by bartjkdp** [comment]
Dit heb ik nogmaals getest!

**Comment by violetmeerdink** [comment]
nieuw punt toegevoegd (bovenin opsomming) bij uploadveld wordt de uitlijning raar als ik naar rechts scroll.
![knipsel](https://user-images.githubusercontent.com/34913358/34478059-fe79ceaa-ef9e-11e7-8f32-477c5800d006.PNG)

**Comment by bartjkdp** [comment]
@violetmeerdink  wat is je zoom-niveau?

**Comment by jfaasen** [comment]
IE styling bij agenda items:

![afbeelding](https://user-images.githubusercontent.com/34096240/36100435-896f0e08-1006-11e8-9dff-33b24e0f3d34.png)

**Comment by jfaasen** [comment]
IE en Chrome probleem notificaties: als je op rode belletje klikt en wil scrollen sluit scherm zich
![afbeelding](https://user-images.githubusercontent.com/34096240/36102874-ec70ed58-100d-11e8-83fd-0432404178fc.png)

**Comment by jfaasen** [comment]
Evenementen: in IE zie je geuploade foto in groep niet terug. Vlak blijft wit. Zie evenement preservation als voorbeeld: https://kia.pleio.nl/groups/view/41371832/kennisplatform-preservation/events

**Comment by bartjkdp** [comment]
- Probleem met eventfoto is opgelost in e2e25ef
- Probleem met agenda item styling is opgelost in b787aa6
- Probleem met notificaties die wegspringen in IE is opgelost in 2f0475b
