### ISSUE TITLE
Bewerken groep: aanpassen tekstvakken

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#74]
Er zijn in het menu 'groep bewerken' nu twee opties voor tekstvakken:
1. Beschrijving
2. Introductie
Het is nu onduidelijk wat van beide tekstvakken de functie en de uiteindelijke plaatsing is.

- tekstvak 1 'beschrijving' is de beschrijving  van de groep: wat is het onderwerp van groep, voor wie is het interessant, ed. Zichtbaar voor niet-leden m.a.w. een advertentie voor je groep. 
- tekstvak 2 'introductie' is voor leden van de groep. Wordt zichtbaar bovenin de homepagina van de groep. Hier kan de groepsbeheerder een memo plaatsen. Groepsleden kunnen de memo wegklikken, als de beheerder een nieuw memo heeft geschreven wordt deze weer zichtbaar. 

Afgesproken dat:

- [ ] Tekstvak  2 'introductie' hoort niet thuis in bij 'groep bewerken'. Moet hier uit worden verwijderd (PRIO 1)

- [x] Naam tekstvak 1 'beschrijving' aanpassen naar: 'beschrijving voor niet-leden'

- [x] Tekstvak 2 'introductie' wordt een soort widget op de homepagina van de groep, altijd zichtbaar voor de beheerder. 

- [x] Naam tekstvak 2 'introductie' aanpassen naar: memo voor leden

**Comment by bartjkdp** [comment]
Ik zou graag een nieuwe Prio 2 ticket willen aanmaken voor het verplaatsen van de introductie naar de groep-pagina. Dat is wat meer werk.

**Comment by jfaasen** [comment]
@bartjkdp , woensdag even overleg hierover. Overigens is punt twee nog niet aangepast maar wel afgevinkt.

**Comment by bartjkdp** [comment]
We hebben 'm samen gecheckt. Kan gesloten worden, komt een nieuw ticket om de functionaliteit  te verplaatsen in #98
