### ISSUE TITLE
Bestanden: odt: schrijf- en leesrechten

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#76]
Bij het opslaan van een bestand heb je voor leesrechten maar twee opties:
- alleen de eigenaar
- ingelogde gebruikers

- [ ] Er zou ook een optie 'leden van 'groep'' moeten zijn

Daarnaast kun je de schrijfrechten bij het opslaan niet aanpassen. 

- [ ] bij opslaan van ODT-bestand ook schrijfrechten laten aanpassen

**Comment by bartjkdp** [comment]
Opgelost in 86968ea

**Comment by jfaasen** [comment]
@bartjkdp lees- en schrijfrechten werken alleen het standaard niveau is niet het groepsniveau. Wil je dit nog aanpassen?

**Comment by bartjkdp** [comment]
Ik kan dit niet reproduceren, ik zie gewoon de groep in zowel lees als schrijfrechten:

![image](https://user-images.githubusercontent.com/5213690/34905388-d4b04f74-f857-11e7-8fec-bc7ef4708bdf.png)

**Comment by jfaasen** [comment]
Werkt inmiddels inderdaad zoals het zou moeten, kan gesloten worden.
