### ISSUE TITLE
Bestand: odt-editor: niet opslaan vanaf submap

### ISSUE THREAD

**Issue by SaskiavdM** [Pleio/pleio_template#77]
Als je de editor opent vanuit een submap, en het bestand vervolgens opslaat, krijg je wel de melding dat het bestand is opgeslagen. Maar het bestand staat vervolgens nergens in de bestandenwidget. 
Als je de editor vanuit de hoofdmap opent gaat het wel goed.

**Comment by bartjkdp** [comment]
Opgelost in aceb761

**Comment by jfaasen** [comment]
Werkt nu wel, kan gesloten worden
