### ISSUE TITLE
Stijling van e-mailtjes instelbaar maken met primaire kleur

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#78]

**Comment by bartjkdp** [comment]
Opgelost in 1730473

**Comment by bartjkdp** [comment]
Opgelost in 1730473

**Comment by jfaasen** [comment]
@bartjkdp kun je even toelichten waar je dit kunt instellen (en dus testen).

**Comment by bartjkdp** [comment]
Dit kun je, net als alle andere kleuren, instellen in /admin/plugin_settings/pleio_template. De headerkleur is gelijk aan de primaire kleur.

**Comment by jfaasen** [comment]
Hoi Bart,
Bij KIA ziet het er zo uit. Ligt dit aan css code uit 'oude site' zo ja belangrijk om rekening mee te houden voor sites die over willen. Wij moeten dus ook e.e.a. aanpassen 
![afbeelding](https://user-images.githubusercontent.com/34096240/34944027-49747356-f9fe-11e7-9507-91709425f675.png)

**Comment by bartjkdp** [comment]
De kleurcode was niet goed ingesteld, er stond #000 in plaats van #000000

Ik krijg de mail nu zo:

![image](https://user-images.githubusercontent.com/5213690/34947944-fe53357a-fa0b-11e7-8269-11f8c658d930.png)

Jij ook?

**Comment by jfaasen** [comment]
Yes, werkt nu goed. dat indien er een icoon aanwezig is op de site deze ook terug zou komen. Hebben we het nog wel over. Geen prio. Voor nu afgerond.
