### ISSUE TITLE
Profiel: Mogelijkheid toevoegen om een bericht te sturen aan gebruiker via e-mail [4]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#79]

**Comment by violetmeerdink** [comment]
Ha Bart, kwam er gisteren ook achter in de praktijk dat het heel handig is als je iemnd meteen kan mailen als je het profiel bekijkt.

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#157
