### ISSUE TITLE
Evenementen: een aantal verbeterpunten [1]

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#8]

**Comment by bartjkdp** [comment]
Opgelost in e230e39

**Comment by jfaasen** [comment]
@SaskiavdM wil jij nog even testen voor hotmail (outlook.com) en google gmail. Calender en Outlook werkt. Als het bij jouw werkt mag je hem sluiten en testlabel verwijderen.

**Comment by SaskiavdM** [comment]
Google: werkt, maar..
- pakt eindtijd evenement niet mee
- pakt tags en externe link niet (weet niet of dat de bedoeling was)

Outlook: idem als Google

**Comment by SaskiavdM** [comment]
Verder bij evenementen:
- het is mogelijk dat de eindtijd van het evenement voor de begintijd staat.
- eindtijd zie ik verder nergens terug, tenzij ik het evenement 'bewerk'
- locatie staat in het evenement direct achter het tijdstip geplakt, geen spatie oid
![image](https://user-images.githubusercontent.com/34911394/34640600-fd2068ca-f2f5-11e7-85c5-173982ce912b.png)

**Comment by bartjkdp** [comment]
De wijzigingen heb ik doorgevoerd. De einddtijd wordt nu goed weergegeven, goed geexporteerd. Het toevoegen bij IE werkt nu ook beter. Tags worden niet gexporteerd, maar er wordt nu wel de link naar het evenement meegestuurd in de beschrijving. 832c5a2

**Comment by SaskiavdM** [comment]
eindtijd is goed zichtbaar evenals locatie. De worden ook goed geëxporteerd. Maar:

- [ ] het is nog steeds mogelijk om een eindtijd in te voren bij het event die voor de begintijd ligt!

**Comment by bartjkdp** [comment]
Dat is wel zo. De vraag is hoe groot dit probleem echt is. Wanneer ik dit wil oplossen moet ik het een en ander fixen, want formulier validatie wordt nu op veld-niveau gedaan. Als je dit zou willen doen moet je ook validatie op formulier-niveau introduceren (het gaat om twee verschillende velden). Voor nu ga ik deze daarom niet oplossen.
