### ISSUE TITLE
Admin: foutmelding bij lidmaatschapsaanvragen

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#80]
![afbeelding](https://user-images.githubusercontent.com/34096240/34653155-176ad15a-f3e8-11e7-89c4-032fd4a3d381.png)

na goedkeuring blijft verzoek staan en krijg je bovenstaande mededeling.

**Comment by bartjkdp** [comment]
Dit probleem komt voor wanneer de gebruiker al geimporteerd is op de deelsite en de gebruiker gelijktijdig een lidmaatschapsverzoek heeft gedaan. De oplossing is om het lidmaatschapsverzoek af te wijzen. De gebruiker heeft immers al toegang tot de site. Er verandert niets aan de permissies die de gebruiker al heeft.

**Comment by jfaasen** [comment]
Hoi Bart,
net procedure gevolgd van lidmaatschap aanvragen met mijn testaccount. Aanvraag komt netjes binnen. Als ik hem wil goedkeuren krijg ik de volgende foutmelding:

![afbeelding](https://user-images.githubusercontent.com/34096240/34731809-bb131336-f563-11e7-9744-a1e033991d04.png)

Die kreeg Sandra dus ook.

**Comment by bartjkdp** [comment]
Aha dat verklaart. Dit komt inderdaad door een recente wijziging in het pleio template. Even een kwestie van plugin uit en weer aan, en dan krijg je deze foutmelding niet meer. Ik heb het inmiddels voor jullie gedaan.
