### ISSUE TITLE
Nieuwsbrief: wat gebeurt er bij overgang en komt deze wel of niet terug en in welke vorm

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#86]
Iets om over na te denken en met RVO te bespreken.

**Comment by bartjkdp** [comment]
Voorstel voor nu is om een eenvoudige nieuwsbrief-tool terug te laten komen in het admin-panel. Met deze tool kun je wel eenvoudig een bericht aan alle gebruikers sturen, maar heb je niet de geavanceerde opties met de templates en het archief. Voor eenvoudig gebruik voldoet de functie dan, voor geavanceerd gebruik kunnen gebruikers uitwijken naar een gespecialiseerd alternatief.

**Comment by bartjkdp** [comment]
Wat ik nu heb gedaan is (toch) het oude template beschikbaar gemaakt op /newsletter. Je kunt de oude nieuwsbrieffunctie dus gewoon gebruiken in combinatie met het nieuwe template.
