### ISSUE TITLE
Agenda: tijden aankunnen passen in de agenda werkt niet!

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#88]

**Comment by bartjkdp** [comment]
Dit kan ik niet reproduceren? Waar en hoe?

**Comment by ziemerink** [comment]
Ik heb dit in safari, in FireFox krijg ik wel een dropdownmenu menu waaruit ik een keuze kan maken! Wellicht zou het makkelijker zijn als je ook gewoon met dubbelklik de tijd kunt aanpassen!

**Comment by bartjkdp** [comment]
Opgelost in 21d9c24
