### ISSUE TITLE
Agenda: Je aanmelden voor een agenda item is in sommige gevallen niet duidelijk, voorstel is om er een witte achtergrond achter te zetten:

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#91]
![schermafbeelding 2018-01-13 om 13 07 11](https://user-images.githubusercontent.com/1875858/34905923-1567de28-f863-11e7-99b8-973553ce31e4.png)

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#159
