### ISSUE TITLE
Instelbaar maken om de knop "delen" aan of uit te zetten

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#92]
<img width="619" alt="schermafbeelding_2018-01-14_om_06_12_00" src="https://user-images.githubusercontent.com/1875858/34913040-2b907dec-f8f2-11e7-8eab-b1244caa1c46.png">

**Comment by jfaasen** [comment]
@ziemerink kun je toelichten wat je bedoelt. Op site niveau door beheerders of per item?

**Comment by ziemerink** [comment]
@jfaasen Per content type zou het mooiste zijn maar voor nu zou het al afdoende zijn om het gewoon wel of niet aan te zetten!

**Comment by bartjkdp** [comment]
This issue was moved to Pleio/beheer#176
