### ISSUE TITLE
Piwik: zorgen dat piwik van AZ Piwik weer gekoppeld kan worden aan energieslag

### ISSUE THREAD

**Issue by jfaasen** [Pleio/pleio_template#95]
N.B. gaat bestaande Piwik (via Pleio) wel mee over met omzetting bij het template zonder gegevens verlies?

**Comment by bartjkdp** [comment]
Vooralsnog kon je alleen de Pleio Piwik koppelen. Ik heb zojuist een wijziging toegevoegd (d46d51b) waarmee je ook andere Piwik's zoals die van AZ kan koppelen. Gegevens gaan gewoon mee bij overzetten van template.

**Comment by jfaasen** [comment]
Jose heeft bevestigd dat het werkt.
