### ISSUE TITLE
Site https://istrategie.pleio.nl niet ingelogd ziet er niet uit

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio_template#97]
<img width="1371" alt="schermafbeelding 2018-01-17 om 09 40 00" src="https://user-images.githubusercontent.com/1875858/35033320-8355657c-fb6a-11e7-9662-b4bdfecad933.png">

**Comment by ziemerink** [comment]
De plug-in HTML Pages even uitgezet waardoor de site wel werkt maar de opgemaakte inlog pagina niet!

**Comment by bartjkdp** [comment]
Een oplossing is gecommit in 2d97543
